package domain

import "github.com/0xsj/overwatch-backend/pkg/errors"

var (
	ErrIDRequired                = errors.New(errors.Invalid, "an identifier is required")
	ErrWorkspaceRequired         = errors.New(errors.Invalid, "a brief belongs to an investigation")
	ErrTimeRequired              = errors.New(errors.Invalid, "a brief needs an instant")
	ErrTitleRequired             = errors.New(errors.Invalid, "a brief needs a title")
	ErrTitleTooLong              = errors.New(errors.Invalid, "that brief title is too long")
	ErrQuestionRequired          = errors.New(errors.Invalid, "a brief needs an investigation question")
	ErrQuestionTooLong           = errors.New(errors.Invalid, "that investigation question is too long")
	ErrAccountTooLong            = errors.New(errors.Invalid, "that current account is too long")
	ErrAlternativesTooLong       = errors.New(errors.Invalid, "those alternatives are too long")
	ErrLimitationsTooLong        = errors.New(errors.Invalid, "those limitations are too long")
	ErrNextStepsTooLong          = errors.New(errors.Invalid, "those next steps are too long")
	ErrTooManyObservations       = errors.New(errors.Invalid, "a brief can cite at most twelve observations")
	ErrTooManyClusters           = errors.New(errors.Invalid, "a brief can link at most eight evidence clusters")
	ErrTooManyQuestions          = errors.New(errors.Invalid, "a brief can link at most eight questions")
	ErrTooManyConnections        = errors.New(errors.Invalid, "a brief can link at most eight connections")
	ErrTooManyEvents             = errors.New(errors.Invalid, "a brief can link at most eight events")
	ErrDuplicateObservation      = errors.New(errors.Invalid, "a brief cannot cite the same observation twice")
	ErrDuplicateCluster          = errors.New(errors.Invalid, "a brief cannot link the same evidence cluster twice")
	ErrDuplicateQuestion         = errors.New(errors.Invalid, "a brief cannot link the same question twice")
	ErrDuplicateConnection       = errors.New(errors.Invalid, "a brief cannot link the same connection twice")
	ErrDuplicateEvent            = errors.New(errors.Invalid, "a brief cannot link the same event twice")
	ErrNotFound                  = errors.New(errors.NotFound, "brief")
	ErrQuestionSnapshotMissing   = errors.New(errors.NotFound, "linked investigation question")
	ErrConnectionSnapshotMissing = errors.New(errors.NotFound, "linked investigation connection")
	ErrEventSnapshotMissing      = errors.New(errors.NotFound, "linked reported event")
	ErrClusterSnapshotMissing    = errors.New(errors.NotFound, "linked evidence cluster")
	ErrInvalidHandoffAccessMode  = errors.New(errors.Invalid, "invalid handoff access mode")
	ErrReviewStateInvalid        = errors.New(errors.Invalid, "choose approve or request changes")
	ErrReviewNoteRequired        = errors.New(errors.Invalid, "a note is required when requesting changes")
	ErrReviewNoteTooLong         = errors.New(errors.Invalid, "that review note is too long")
	ErrReviewerNotInWorkspace    = errors.New(errors.Invalid, "the reviewer must be a member of this investigation")
	ErrCommentRequired           = errors.New(errors.Invalid, "a handoff comment is required")
	ErrCommentTooLong            = errors.New(errors.Invalid, "that handoff comment is too long")
	ErrShareTokenRequired        = errors.New(errors.Invalid, "a handoff share needs a token")
)
