// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package findingdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FindingDetail struct {
	ID         pgtype.UUID
	FindingID  pgtype.UUID
	Field      string
	Value      string
	MappingID  pgtype.UUID
	ArtifactID pgtype.UUID
	SeenAt     pgtype.Timestamptz
}

type FindingFinding struct {
	ID                   pgtype.UUID
	WorkspaceID          pgtype.UUID
	ToolID               pgtype.UUID
	Signature            string
	FragmentID           pgtype.UUID
	FragmentKind         string
	FragmentValue        string
	State                string
	Reason               pgtype.Text
	DecidedBy            pgtype.UUID
	DecidedAt            pgtype.Timestamptz
	Severity             string
	Claimant             string
	Actor                pgtype.UUID
	Confidence           pgtype.Float8
	Basis                pgtype.Text
	AssessedAt           pgtype.Timestamptz
	SupersededSeverity   pgtype.Text
	SupersededClaimant   pgtype.Text
	SupersededActor      pgtype.UUID
	SupersededConfidence pgtype.Float8
	SupersededBasis      pgtype.Text
	SupersededAt         pgtype.Timestamptz
	FirstSeen            pgtype.Timestamptz
	LastSeen             pgtype.Timestamptz
	Sightings            int32
	InvocationID         pgtype.UUID
	ArtifactID           pgtype.UUID
	MappingID            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
}
