// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NoteNote struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	SubjectKind  pgtype.Text
	SubjectValue pgtype.Text
	ContextKind  pgtype.Text
	ContextID    pgtype.UUID
	Body         string
	AuthorID     pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
