// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: note.sql

package notedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allSummaryNotes = `-- name: AllSummaryNotes :many
select id, workspace_id, subject_kind, subject_value, body,
       author_id, created_at, updated_at
from note.note
where workspace_id = $1 and subject_kind is null
order by created_at desc, id desc
`

// Deliverables include every subjectless note, without the interactive list cap.
func (q *Queries) AllSummaryNotes(ctx context.Context, workspaceID pgtype.UUID) ([]NoteNote, error) {
	rows, err := q.db.Query(ctx, allSummaryNotes, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NoteNote{}
	for rows.Next() {
		var i NoteNote
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SubjectKind,
			&i.SubjectValue,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteNote = `-- name: DeleteNote :execrows
delete from note.note where id = $1 and workspace_id = $2
`

type DeleteNoteParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNote = `-- name: InsertNote :exec
insert into note.note (
    id, workspace_id, subject_kind, subject_value, body,
    author_id, created_at, updated_at
) values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertNoteParams struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	SubjectKind  pgtype.Text
	SubjectValue pgtype.Text
	Body         string
	AuthorID     pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertNote(ctx context.Context, arg InsertNoteParams) error {
	_, err := q.db.Exec(ctx, insertNote,
		arg.ID,
		arg.WorkspaceID,
		arg.SubjectKind,
		arg.SubjectValue,
		arg.Body,
		arg.AuthorID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const noteByID = `-- name: NoteByID :one
select id, workspace_id, subject_kind, subject_value, body,
       author_id, created_at, updated_at
from note.note where id = $1 and workspace_id = $2
`

type NoteByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

// BOTH IDS. A note read without its engagement is another client's.
func (q *Queries) NoteByID(ctx context.Context, arg NoteByIDParams) (NoteNote, error) {
	row := q.db.QueryRow(ctx, noteByID, arg.ID, arg.WorkspaceID)
	var i NoteNote
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubjectKind,
		&i.SubjectValue,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const notesForWorkspace = `-- name: NotesForWorkspace :many
select id, workspace_id, subject_kind, subject_value, body,
       author_id, created_at, updated_at
from note.note
where workspace_id = $1
  and ($2::text is null or subject_kind = $2::text)
  and ($3::text is null or subject_value = $3::text)
  and (not $4::boolean or subject_kind is null)
order by created_at desc
limit $5::int
`

type NotesForWorkspaceParams struct {
	WorkspaceID pgtype.UUID
	Kind        pgtype.Text
	Value       pgtype.Text
	SummaryOnly bool
	Page        int32
}

// The list. `subject` NULL means EVERY note; the two-argument form asks for one
// subject, and the empty-string form asks for the engagement summary only —
// three questions one query answers, because they differ by a predicate rather
// than by shape.
func (q *Queries) NotesForWorkspace(ctx context.Context, arg NotesForWorkspaceParams) ([]NoteNote, error) {
	rows, err := q.db.Query(ctx, notesForWorkspace,
		arg.WorkspaceID,
		arg.Kind,
		arg.Value,
		arg.SummaryOnly,
		arg.Page,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NoteNote{}
	for rows.Next() {
		var i NoteNote
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SubjectKind,
			&i.SubjectValue,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveNote = `-- name: SaveNote :execrows
update note.note set body = $3, updated_at = $4
where id = $1 and workspace_id = $2
`

type SaveNoteParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Body        string
	UpdatedAt   pgtype.Timestamptz
}

// The body and the clock, and NOTHING ELSE. The author never moves and neither
// does created_at — an edit is that person revising their own statement.
func (q *Queries) SaveNote(ctx context.Context, arg SaveNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveNote,
		arg.ID,
		arg.WorkspaceID,
		arg.Body,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
