package domain

import "github.com/0xsj/overwatch-backend/pkg/errors"

var (
	ErrIDRequired                       = errors.New(errors.Invalid, "an identifier is required")
	ErrWorkspaceRequired                = errors.New(errors.Invalid, "an event belongs to an investigation")
	ErrTimeRequired                     = errors.New(errors.Invalid, "an event time precision is required")
	ErrTimeUnknown                      = errors.New(errors.Invalid, "not an event time precision this system knows")
	ErrTitleRequired                    = errors.New(errors.Invalid, "an event needs a title")
	ErrTitleTooLong                     = errors.New(errors.Invalid, "that event title is too long")
	ErrDescriptionTooLong               = errors.New(errors.Invalid, "that event description is too long")
	ErrTimeTextTooLong                  = errors.New(errors.Invalid, "that reported time is too long")
	ErrLocationTooLong                  = errors.New(errors.Invalid, "that event location is too long")
	ErrSortDateInvalid                  = errors.New(errors.Invalid, "event ordering date must be YYYY-MM-DD")
	ErrObservationTooMany               = errors.New(errors.Invalid, "an event can cite at most eight observations")
	ErrDuplicateObservation             = errors.New(errors.Invalid, "an event cannot cite the same observation twice")
	ErrParticipantTooMany               = errors.New(errors.Invalid, "an event can name at most eight participant records")
	ErrDuplicateParticipant             = errors.New(errors.Invalid, "an event cannot name the same participant record twice")
	ErrParticipantRoleUnknown           = errors.New(errors.Invalid, "not an event participant role this system knows")
	ErrLocationRecordKind               = errors.New(errors.Invalid, "an event location record must be a place record")
	ErrReconciliationUnknown            = errors.New(errors.Invalid, "not an event reconciliation decision this system knows")
	ErrReconciliationRequired           = errors.New(errors.Invalid, "an event reconciliation needs a rationale")
	ErrAccountRequired                  = errors.New(errors.Invalid, "a preferred source account is required for this decision")
	ErrClusterTitleRequired             = errors.New(errors.Invalid, "an event cluster needs a title")
	ErrClusterDescriptionTooLong        = errors.New(errors.Invalid, "that event cluster description is too long")
	ErrClusterEventCount                = errors.New(errors.Invalid, "an event cluster needs between two and twelve events")
	ErrDuplicateClusterEvent            = errors.New(errors.Invalid, "an event cluster cannot contain the same event twice")
	ErrClusterStateUnknown              = errors.New(errors.Invalid, "not an event cluster review state this system knows")
	ErrClusterReviewRequired            = errors.New(errors.Invalid, "accepted or rejected event clusters need a review note")
	ErrEventRelationshipSelf            = errors.New(errors.Invalid, "an event relationship needs two different events")
	ErrEventRelationshipUnknown         = errors.New(errors.Invalid, "not an event relationship type this system knows")
	ErrEventRelationshipRationale       = errors.New(errors.Invalid, "an event relationship needs a rationale")
	ErrDuplicateRelationshipObservation = errors.New(errors.Invalid, "an event relationship cannot cite the same observation on both sides")
	ErrEventRelationshipStateUnknown    = errors.New(errors.Invalid, "not an event relationship review state this system knows")
	ErrEventRelationshipReviewRequired  = errors.New(errors.Invalid, "accepted or rejected event relationships need a review note")
	ErrNotFound                         = errors.New(errors.NotFound, "event")
)
