// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tooldb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ToolMapping struct {
	ID         pgtype.UUID
	OrgID      pgtype.UUID
	ToolID     pgtype.UUID
	Field      string
	Expression string
	Version    int32
	State      string
	CreatedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	PromotedAt pgtype.Timestamptz
	RetiredAt  pgtype.Timestamptz
}

type ToolTool struct {
	ID               pgtype.UUID
	OrgID            pgtype.UUID
	Name             string
	Argv             string
	Intensity        string
	Status           string
	Version          int32
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ArchivedAt       pgtype.Timestamptz
	Consumes         pgtype.Text
	Produces         pgtype.Text
	SuccessExitCodes []int32
}
