// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tool.sql

package tooldb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findingToolsWithNoSignature = `-- name: FindingToolsWithNoSignature :many
select t.id, t.name, t.created_at
from tool.tool t
where t.org_id = $1 and t.status <> 'archived' and t.produces = 'finding'
  and exists (
      select 1 from tool.mapping m where m.tool_id = t.id and m.state = 'live'
  )
  and not exists (
      select 1 from tool.mapping m
      where m.tool_id = t.id and m.state = 'live' and m.role = 'signature'
  )
order by t.created_at
`

type FindingToolsWithNoSignatureRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

// decisions/0041 §2's quiet failure: a tool declaring `produces: finding` and no
// `signature` mapping extracts NOTHING, and a scan that produces no findings
// looks exactly like a clean one.
//
// It requires at least one live mapping, because a tool with none at all is the
// symptom above and reporting it twice would double-count one problem.
func (q *Queries) FindingToolsWithNoSignature(ctx context.Context, orgID pgtype.UUID) ([]FindingToolsWithNoSignatureRow, error) {
	rows, err := q.db.Query(ctx, findingToolsWithNoSignature, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingToolsWithNoSignatureRow{}
	for rows.Next() {
		var i FindingToolsWithNoSignatureRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMapping = `-- name: InsertMapping :exec
insert into tool.mapping (
    id, org_id, tool_id, field, expression, version, state, role,
    created_by, created_at, promoted_at, retired_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertMappingParams struct {
	ID         pgtype.UUID
	OrgID      pgtype.UUID
	ToolID     pgtype.UUID
	Field      string
	Expression string
	Version    int32
	State      string
	Role       string
	CreatedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	PromotedAt pgtype.Timestamptz
	RetiredAt  pgtype.Timestamptz
}

func (q *Queries) InsertMapping(ctx context.Context, arg InsertMappingParams) error {
	_, err := q.db.Exec(ctx, insertMapping,
		arg.ID,
		arg.OrgID,
		arg.ToolID,
		arg.Field,
		arg.Expression,
		arg.Version,
		arg.State,
		arg.Role,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.PromotedAt,
		arg.RetiredAt,
	)
	return err
}

const insertTool = `-- name: InsertTool :exec
insert into tool.tool (
    id, org_id, name, argv, intensity, status, version,
    created_by, created_at, updated_at, archived_at, consumes, produces,
    success_exit_codes
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertToolParams struct {
	ID               pgtype.UUID
	OrgID            pgtype.UUID
	Name             string
	Argv             string
	Intensity        string
	Status           string
	Version          int32
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ArchivedAt       pgtype.Timestamptz
	Consumes         pgtype.Text
	Produces         pgtype.Text
	SuccessExitCodes []int32
}

func (q *Queries) InsertTool(ctx context.Context, arg InsertToolParams) error {
	_, err := q.db.Exec(ctx, insertTool,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Argv,
		arg.Intensity,
		arg.Status,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ArchivedAt,
		arg.Consumes,
		arg.Produces,
		arg.SuccessExitCodes,
	)
	return err
}

const liveMappingFor = `-- name: LiveMappingFor :one
select id, org_id, tool_id, field, expression, version, state,
       created_by, created_at, promoted_at, retired_at, role
from tool.mapping where tool_id = $1 and field = $2 and state = 'live'
`

type LiveMappingForParams struct {
	ToolID pgtype.UUID
	Field  string
}

func (q *Queries) LiveMappingFor(ctx context.Context, arg LiveMappingForParams) (ToolMapping, error) {
	row := q.db.QueryRow(ctx, liveMappingFor, arg.ToolID, arg.Field)
	var i ToolMapping
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ToolID,
		&i.Field,
		&i.Expression,
		&i.Version,
		&i.State,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PromotedAt,
		&i.RetiredAt,
		&i.Role,
	)
	return i, err
}

const liveMappingsForToolByRole = `-- name: LiveMappingsForToolByRole :many
select id, org_id, tool_id, field, expression, version, state,
       created_by, created_at, promoted_at, retired_at, role
from tool.mapping
where tool_id = $1 and state = 'live' and role <> 'attribute'
order by role
`

// What EXTRACTION resolves a record's subject and its provenance from —
// decisions/0040 §1. By ROLE and never by field name.
//
// Two rows at most, and the partial unique indexes are what say so; this query
// does not assume it, because a query that returns one row where the index
// allows two is a silent truncation.
func (q *Queries) LiveMappingsForToolByRole(ctx context.Context, toolID pgtype.UUID) ([]ToolMapping, error) {
	rows, err := q.db.Query(ctx, liveMappingsForToolByRole, toolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolMapping{}
	for rows.Next() {
		var i ToolMapping
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ToolID,
			&i.Field,
			&i.Expression,
			&i.Version,
			&i.State,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PromotedAt,
			&i.RetiredAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mappingByID = `-- name: MappingByID :one
select id, org_id, tool_id, field, expression, version, state,
       created_by, created_at, promoted_at, retired_at, role
from tool.mapping where id = $1 and org_id = $2
`

type MappingByIDParams struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
}

func (q *Queries) MappingByID(ctx context.Context, arg MappingByIDParams) (ToolMapping, error) {
	row := q.db.QueryRow(ctx, mappingByID, arg.ID, arg.OrgID)
	var i ToolMapping
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ToolID,
		&i.Field,
		&i.Expression,
		&i.Version,
		&i.State,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PromotedAt,
		&i.RetiredAt,
		&i.Role,
	)
	return i, err
}

const mappingsForTool = `-- name: MappingsForTool :many
select id, org_id, tool_id, field, expression, version, state,
       created_by, created_at, promoted_at, retired_at, role
from tool.mapping where tool_id = $1 and org_id = $2
order by field, version desc
`

type MappingsForToolParams struct {
	ToolID pgtype.UUID
	OrgID  pgtype.UUID
}

func (q *Queries) MappingsForTool(ctx context.Context, arg MappingsForToolParams) ([]ToolMapping, error) {
	rows, err := q.db.Query(ctx, mappingsForTool, arg.ToolID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolMapping{}
	for rows.Next() {
		var i ToolMapping
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ToolID,
			&i.Field,
			&i.Expression,
			&i.Version,
			&i.State,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PromotedAt,
			&i.RetiredAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextMappingVersion = `-- name: NextMappingVersion :one
select coalesce(max(version), 0)::int + 1
from tool.mapping where tool_id = $1 and field = $2
`

type NextMappingVersionParams struct {
	ToolID pgtype.UUID
	Field  string
}

// coalesce, because the first version of a field has no predecessor and max()
// over no rows is null rather than zero.
func (q *Queries) NextMappingVersion(ctx context.Context, arg NextMappingVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextMappingVersion, arg.ToolID, arg.Field)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setMappingState = `-- name: SetMappingState :execrows
update tool.mapping
set state = $3, promoted_at = $4, retired_at = $5
where id = $1 and org_id = $2
`

type SetMappingStateParams struct {
	ID         pgtype.UUID
	OrgID      pgtype.UUID
	State      string
	PromotedAt pgtype.Timestamptz
	RetiredAt  pgtype.Timestamptz
}

// The ONLY update this table takes. It moves the two lifecycle columns and
// nothing else — the expression is what citations point at.
func (q *Queries) SetMappingState(ctx context.Context, arg SetMappingStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMappingState,
		arg.ID,
		arg.OrgID,
		arg.State,
		arg.PromotedAt,
		arg.RetiredAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const toolByID = `-- name: ToolByID :one
select id, org_id, name, argv, intensity, status, version,
       created_by, created_at, updated_at, archived_at, consumes, produces,
       success_exit_codes
from tool.tool where id = $1 and org_id = $2
`

type ToolByIDParams struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
}

// BOTH IDS. A tool read without its org is another firm's, and a signature that
// cannot express the mistake is worth more than a rule about remembering.
func (q *Queries) ToolByID(ctx context.Context, arg ToolByIDParams) (ToolTool, error) {
	row := q.db.QueryRow(ctx, toolByID, arg.ID, arg.OrgID)
	var i ToolTool
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Argv,
		&i.Intensity,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Consumes,
		&i.Produces,
		&i.SuccessExitCodes,
	)
	return i, err
}

const toolsConsidered = `-- name: ToolsConsidered :one
select count(*)::int from tool.tool where org_id = $1 and status <> 'archived'
`

func (q *Queries) ToolsConsidered(ctx context.Context, orgID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, toolsConsidered, orgID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const toolsForOrg = `-- name: ToolsForOrg :many
select id, org_id, name, argv, intensity, status, version,
       created_by, created_at, updated_at, archived_at, consumes, produces,
       success_exit_codes
from tool.tool
where org_id = $1 and ($2::bool or status <> 'archived')
order by lower(name)
`

type ToolsForOrgParams struct {
	OrgID           pgtype.UUID
	IncludeArchived bool
}

func (q *Queries) ToolsForOrg(ctx context.Context, arg ToolsForOrgParams) ([]ToolTool, error) {
	rows, err := q.db.Query(ctx, toolsForOrg, arg.OrgID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolTool{}
	for rows.Next() {
		var i ToolTool
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Argv,
			&i.Intensity,
			&i.Status,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Consumes,
			&i.Produces,
			&i.SuccessExitCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toolsNobodyReads = `-- name: ToolsNobodyReads :many
select t.id, t.name, t.produces, t.created_at
from tool.tool t
where t.org_id = $1 and t.status <> 'archived'
  and not exists (
      select 1 from tool.mapping m
      where m.tool_id = t.id and m.state = 'live'
  )
order by t.created_at
`

type ToolsNobodyReadsRow struct {
	ID        pgtype.UUID
	Name      string
	Produces  pgtype.Text
	CreatedAt pgtype.Timestamptz
}

// A tool with NO LIVE MAPPING. It spawns, its bytes are stored and citable, and
// nothing is read out of them — a true and ordinary state for a tool nobody has
// taught this system yet, and indistinguishable from one that found nothing.
//
// LIVE tools only: an archived one producing nothing is not a symptom.
func (q *Queries) ToolsNobodyReads(ctx context.Context, orgID pgtype.UUID) ([]ToolsNobodyReadsRow, error) {
	rows, err := q.db.Query(ctx, toolsNobodyReads, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolsNobodyReadsRow{}
	for rows.Next() {
		var i ToolsNobodyReadsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Produces,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTool = `-- name: UpdateTool :execrows
update tool.tool
set argv = $3, intensity = $4, status = $5, version = $6,
    updated_at = $7, archived_at = $8, consumes = $9, produces = $10,
    success_exit_codes = $11
where id = $1 and org_id = $2 and version = $12
`

type UpdateToolParams struct {
	ID               pgtype.UUID
	OrgID            pgtype.UUID
	Argv             string
	Intensity        string
	Status           string
	Version          int32
	UpdatedAt        pgtype.Timestamptz
	ArchivedAt       pgtype.Timestamptz
	Consumes         pgtype.Text
	Produces         pgtype.Text
	SuccessExitCodes []int32
	Version_2        int32
}

// The column list must match what the domain can change. It did not once, in
// identity, and the command returned a correctly-moved record having moved
// nothing.
func (q *Queries) UpdateTool(ctx context.Context, arg UpdateToolParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTool,
		arg.ID,
		arg.OrgID,
		arg.Argv,
		arg.Intensity,
		arg.Status,
		arg.Version,
		arg.UpdatedAt,
		arg.ArchivedAt,
		arg.Consumes,
		arg.Produces,
		arg.SuccessExitCodes,
		arg.Version_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
