// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package observationdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ObservationCitationShare struct {
	ID            pgtype.UUID
	WorkspaceID   pgtype.UUID
	SourceID      pgtype.UUID
	ObservationID pgtype.UUID
	CreatedBy     pgtype.UUID
	TokenDigest   string
	CreatedAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	RevokedBy     pgtype.UUID
}

type ObservationManual struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	SourceID     pgtype.UUID
	CaptureID    pgtype.UUID
	Statement    string
	Quote        []byte
	QuoteStart   int32
	QuoteEnd     int32
	Locator      string
	Author       pgtype.UUID
	RecordedAt   pgtype.Timestamptz
	ExtractionID pgtype.UUID
}

type ObservationObservation struct {
	ID             pgtype.UUID
	WorkspaceID    pgtype.UUID
	SubjectKind    string
	SubjectValue   string
	Field          string
	Value          string
	InvocationID   pgtype.UUID
	ArtifactID     pgtype.UUID
	MappingID      pgtype.UUID
	MappingVersion int32
	ObservedAt     pgtype.Timestamptz
	RecordedAt     pgtype.Timestamptz
	Role           string
}

type ObservationUnmapped struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	InvocationID pgtype.UUID
	ArtifactID   pgtype.UUID
	Path         string
	Seen         int32
	Sample       pgtype.Text
	RecordedAt   pgtype.Timestamptz
}
