// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package observationdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ObservationObservation struct {
	ID             pgtype.UUID
	WorkspaceID    pgtype.UUID
	SubjectKind    string
	SubjectValue   string
	Field          string
	Value          string
	InvocationID   pgtype.UUID
	ArtifactID     pgtype.UUID
	MappingID      pgtype.UUID
	MappingVersion int32
	ObservedAt     pgtype.Timestamptz
	RecordedAt     pgtype.Timestamptz
}

type ObservationUnmapped struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	InvocationID pgtype.UUID
	ArtifactID   pgtype.UUID
	Path         string
	Seen         int32
	Sample       pgtype.Text
	RecordedAt   pgtype.Timestamptz
}
