// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observation.sql

package observationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const extractionQuality = `-- name: ExtractionQuality :one
select
    (select count(distinct o.mapping_id)::int from observation.observation o
     where o.workspace_id = $1::uuid
       and o.invocation_id = $2::uuid) as mapped,
    (select count(*)::int from observation.observation o
     where o.workspace_id = $1::uuid
       and o.invocation_id = $2::uuid) as observations,
    (select count(*)::int from observation.unmapped u
     where u.workspace_id = $1::uuid
       and u.invocation_id = $2::uuid) as left_alone,
    (select count(distinct o.field)::int from observation.observation o
     where o.workspace_id = $1::uuid
       and o.invocation_id = $2::uuid) as fields
`

type ExtractionQualityParams struct {
	Workspace  pgtype.UUID
	Invocation pgtype.UUID
}

type ExtractionQualityRow struct {
	Mapped       int32
	Observations int32
	LeftAlone    int32
	Fields       int32
}

// The numbers the whole correction loop is measured by, returned TOGETHER
// because a ratio without its denominator is what 0011 refuses.
//
// **MAPPED IS COUNTED IN PATHS, NOT IN OBSERVATIONS.** It was `count(*)` for an
// hour, which made `FIELDS SEEN = MAPPED + LEFT ALONE` false the moment a
// `.tech[]` flatten produced two values from one path — the walk showed
// `FIELDS SEEN 9` for a record with eight distinct paths. `distinct mapping_id`
// is the right count: a mapping that matched nothing produced no observations
// and correctly does not appear, which is what the draft's "22 became
// observations" means.
func (q *Queries) ExtractionQuality(ctx context.Context, arg ExtractionQualityParams) (ExtractionQualityRow, error) {
	row := q.db.QueryRow(ctx, extractionQuality, arg.Workspace, arg.Invocation)
	var i ExtractionQualityRow
	err := row.Scan(
		&i.Mapped,
		&i.Observations,
		&i.LeftAlone,
		&i.Fields,
	)
	return i, err
}

const insertObservation = `-- name: InsertObservation :exec
insert into observation.observation (
    id, workspace_id, subject_kind, subject_value, field, value,
    invocation_id, artifact_id, mapping_id, mapping_version,
    observed_at, recorded_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertObservationParams struct {
	ID             pgtype.UUID
	WorkspaceID    pgtype.UUID
	SubjectKind    string
	SubjectValue   string
	Field          string
	Value          string
	InvocationID   pgtype.UUID
	ArtifactID     pgtype.UUID
	MappingID      pgtype.UUID
	MappingVersion int32
	ObservedAt     pgtype.Timestamptz
	RecordedAt     pgtype.Timestamptz
}

func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) error {
	_, err := q.db.Exec(ctx, insertObservation,
		arg.ID,
		arg.WorkspaceID,
		arg.SubjectKind,
		arg.SubjectValue,
		arg.Field,
		arg.Value,
		arg.InvocationID,
		arg.ArtifactID,
		arg.MappingID,
		arg.MappingVersion,
		arg.ObservedAt,
		arg.RecordedAt,
	)
	return err
}

const insertUnmapped = `-- name: InsertUnmapped :exec
insert into observation.unmapped (
    id, workspace_id, invocation_id, artifact_id, path, seen, sample, recorded_at
) values ($1, $2, $3, $4, $5, $6, $7, $8)
on conflict (artifact_id, path) do update
set seen = excluded.seen, sample = excluded.sample, recorded_at = excluded.recorded_at
`

type InsertUnmappedParams struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	InvocationID pgtype.UUID
	ArtifactID   pgtype.UUID
	Path         string
	Seen         int32
	Sample       pgtype.Text
	RecordedAt   pgtype.Timestamptz
}

// Re-extracting the same bytes must not double the LEFT ALONE count. The count
// is REPLACED rather than added to, because it is a property of the artifact and
// not of how many times it was read.
func (q *Queries) InsertUnmapped(ctx context.Context, arg InsertUnmappedParams) error {
	_, err := q.db.Exec(ctx, insertUnmapped,
		arg.ID,
		arg.WorkspaceID,
		arg.InvocationID,
		arg.ArtifactID,
		arg.Path,
		arg.Seen,
		arg.Sample,
		arg.RecordedAt,
	)
	return err
}

const observationByID = `-- name: ObservationByID :one
select id, workspace_id, subject_kind, subject_value, field, value,
       invocation_id, artifact_id, mapping_id, mapping_version,
       observed_at, recorded_at
from observation.observation where id = $1 and workspace_id = $2
`

type ObservationByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) ObservationByID(ctx context.Context, arg ObservationByIDParams) (ObservationObservation, error) {
	row := q.db.QueryRow(ctx, observationByID, arg.ID, arg.WorkspaceID)
	var i ObservationObservation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubjectKind,
		&i.SubjectValue,
		&i.Field,
		&i.Value,
		&i.InvocationID,
		&i.ArtifactID,
		&i.MappingID,
		&i.MappingVersion,
		&i.ObservedAt,
		&i.RecordedAt,
	)
	return i, err
}

const observationsForInvocation = `-- name: ObservationsForInvocation :many
select id, workspace_id, subject_kind, subject_value, field, value,
       invocation_id, artifact_id, mapping_id, mapping_version,
       observed_at, recorded_at
from observation.observation
where invocation_id = $1 and workspace_id = $2
order by subject_value, field, observed_at desc
limit $3::int
`

type ObservationsForInvocationParams struct {
	InvocationID pgtype.UUID
	WorkspaceID  pgtype.UUID
	Page         int32
}

func (q *Queries) ObservationsForInvocation(ctx context.Context, arg ObservationsForInvocationParams) ([]ObservationObservation, error) {
	rows, err := q.db.Query(ctx, observationsForInvocation, arg.InvocationID, arg.WorkspaceID, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationObservation{}
	for rows.Next() {
		var i ObservationObservation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SubjectKind,
			&i.SubjectValue,
			&i.Field,
			&i.Value,
			&i.InvocationID,
			&i.ArtifactID,
			&i.MappingID,
			&i.MappingVersion,
			&i.ObservedAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observationsForSubject = `-- name: ObservationsForSubject :many
select id, workspace_id, subject_kind, subject_value, field, value,
       invocation_id, artifact_id, mapping_id, mapping_version,
       observed_at, recorded_at
from observation.observation
where workspace_id = $1 and subject_kind = $2 and subject_value = $3
order by field, observed_at desc
limit $4::int
`

type ObservationsForSubjectParams struct {
	WorkspaceID  pgtype.UUID
	SubjectKind  string
	SubjectValue string
	Page         int32
}

// The asset drawer's read: everything known about one subject. NOT deduplicated
// — two runs a day apart are two statements, and collapsing them loses the
// second date. "The state of each field" is the caller taking the first row per
// field off this, which is what the ordering is for.
func (q *Queries) ObservationsForSubject(ctx context.Context, arg ObservationsForSubjectParams) ([]ObservationObservation, error) {
	rows, err := q.db.Query(ctx, observationsForSubject,
		arg.WorkspaceID,
		arg.SubjectKind,
		arg.SubjectValue,
		arg.Page,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationObservation{}
	for rows.Next() {
		var i ObservationObservation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SubjectKind,
			&i.SubjectValue,
			&i.Field,
			&i.Value,
			&i.InvocationID,
			&i.ArtifactID,
			&i.MappingID,
			&i.MappingVersion,
			&i.ObservedAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subjectsForWorkspace = `-- name: SubjectsForWorkspace :many
select subject_kind, subject_value,
       count(*)::int as observations,
       count(distinct field)::int as fields,
       max(observed_at)::timestamptz as last_seen
from observation.observation
where workspace_id = $1
group by subject_kind, subject_value
order by max(observed_at) desc
limit $2::int
`

type SubjectsForWorkspaceParams struct {
	WorkspaceID pgtype.UUID
	Page        int32
}

type SubjectsForWorkspaceRow struct {
	SubjectKind  string
	SubjectValue string
	Observations int32
	Fields       int32
	LastSeen     pgtype.Timestamptz
}

// Distinct subjects, with how much is known about each. This is what stands in
// for an asset list until `fragment` exists — and it is deliberately a GROUP BY
// over observations rather than a table, because that is what a fragment will
// be a dedup of.
func (q *Queries) SubjectsForWorkspace(ctx context.Context, arg SubjectsForWorkspaceParams) ([]SubjectsForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, subjectsForWorkspace, arg.WorkspaceID, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubjectsForWorkspaceRow{}
	for rows.Next() {
		var i SubjectsForWorkspaceRow
		if err := rows.Scan(
			&i.SubjectKind,
			&i.SubjectValue,
			&i.Observations,
			&i.Fields,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subjectsPerInvocation = `-- name: SubjectsPerInvocation :many
select invocation_id, subject_kind, subject_value,
       max(observed_at)::timestamptz as last_seen
from observation.observation
where workspace_id = $1
group by invocation_id, subject_kind, subject_value
`

type SubjectsPerInvocationRow struct {
	InvocationID pgtype.UUID
	SubjectKind  string
	SubjectValue string
	LastSeen     pgtype.Timestamptz
}

// What each invocation actually SAID something about — coverage's second
// source, decisions/0037.
//
// The first source is what an invocation was AIMED AT, which is what keeps
// `never checked` and `found nothing` apart. This one catches DISCOVERY: a tool
// pointed at a seed produces subjects nobody aimed at, and the check that found
// them has plainly looked at them.
func (q *Queries) SubjectsPerInvocation(ctx context.Context, workspaceID pgtype.UUID) ([]SubjectsPerInvocationRow, error) {
	rows, err := q.db.Query(ctx, subjectsPerInvocation, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubjectsPerInvocationRow{}
	for rows.Next() {
		var i SubjectsPerInvocationRow
		if err := rows.Scan(
			&i.InvocationID,
			&i.SubjectKind,
			&i.SubjectValue,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unmappedForInvocation = `-- name: UnmappedForInvocation :many
select id, workspace_id, invocation_id, artifact_id, path, seen, sample, recorded_at
from observation.unmapped
where invocation_id = $1 and workspace_id = $2
order by seen desc, path
`

type UnmappedForInvocationParams struct {
	InvocationID pgtype.UUID
	WorkspaceID  pgtype.UUID
}

func (q *Queries) UnmappedForInvocation(ctx context.Context, arg UnmappedForInvocationParams) ([]ObservationUnmapped, error) {
	rows, err := q.db.Query(ctx, unmappedForInvocation, arg.InvocationID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationUnmapped{}
	for rows.Next() {
		var i ObservationUnmapped
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InvocationID,
			&i.ArtifactID,
			&i.Path,
			&i.Seen,
			&i.Sample,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
