// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entry.sql

package auditdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const entriesForActor = `-- name: EntriesForActor :many
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at
from audit.entry
where actor = $1
order by occurred_at desc
limit $2
`

type EntriesForActorParams struct {
	Actor string
	Limit int32
}

func (q *Queries) EntriesForActor(ctx context.Context, arg EntriesForActorParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, entriesForActor, arg.Actor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Scope,
			&i.Action,
			&i.Subject,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesForSubject = `-- name: EntriesForSubject :many
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at
from audit.entry
where subject = $1
order by occurred_at desc
limit $2
`

type EntriesForSubjectParams struct {
	Subject string
	Limit   int32
}

func (q *Queries) EntriesForSubject(ctx context.Context, arg EntriesForSubjectParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, entriesForSubject, arg.Subject, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Scope,
			&i.Action,
			&i.Subject,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesForWorkspace = `-- name: EntriesForWorkspace :many
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at
from audit.entry
where workspace_id = $1
order by occurred_at desc
limit $2
`

type EntriesForWorkspaceParams struct {
	WorkspaceID string
	Limit       int32
}

func (q *Queries) EntriesForWorkspace(ctx context.Context, arg EntriesForWorkspaceParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, entriesForWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Scope,
			&i.Action,
			&i.Subject,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entryByID = `-- name: EntryByID :one
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at
from audit.entry
where id = $1
`

func (q *Queries) EntryByID(ctx context.Context, id pgtype.UUID) (AuditEntry, error) {
	row := q.db.QueryRow(ctx, entryByID, id)
	var i AuditEntry
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Scope,
		&i.Action,
		&i.Subject,
		&i.Actor,
		&i.OnBehalfOf,
		&i.WorkspaceID,
		&i.CorrelationID,
		&i.CausationID,
		&i.Detail,
		&i.OccurredAt,
		&i.RecordedAt,
	)
	return i, err
}

const insertEntry = `-- name: InsertEntry :execrows
insert into audit.entry (
    id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
    correlation_id, causation_id, detail, occurred_at, recorded_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
on conflict (event_id) do nothing
`

type InsertEntryParams struct {
	ID            pgtype.UUID
	EventID       pgtype.UUID
	Scope         string
	Action        string
	Subject       string
	Actor         string
	OnBehalfOf    string
	WorkspaceID   string
	CorrelationID pgtype.UUID
	CausationID   pgtype.UUID
	Detail        []byte
	OccurredAt    pgtype.Timestamptz
	RecordedAt    pgtype.Timestamptz
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEntry,
		arg.ID,
		arg.EventID,
		arg.Scope,
		arg.Action,
		arg.Subject,
		arg.Actor,
		arg.OnBehalfOf,
		arg.WorkspaceID,
		arg.CorrelationID,
		arg.CausationID,
		arg.Detail,
		arg.OccurredAt,
		arg.RecordedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
