// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entry.sql

package auditdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const entriesForActor = `-- name: EntriesForActor :many
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at, org_id
from audit.entry
where actor = $1
order by occurred_at desc
limit $2
`

type EntriesForActorParams struct {
	Actor string
	Limit int32
}

func (q *Queries) EntriesForActor(ctx context.Context, arg EntriesForActorParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, entriesForActor, arg.Actor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Scope,
			&i.Action,
			&i.Subject,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesForOrgPage = `-- name: EntriesForOrgPage :many
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at, org_id
from audit.entry
where org_id = $1
  and ($2::timestamptz is null or (occurred_at, id) < ($2::timestamptz, $3::uuid))
order by occurred_at desc, id desc
limit $4
`

type EntriesForOrgPageParams struct {
	OrgID   string
	Column2 pgtype.Timestamptz
	Column3 pgtype.UUID
	Limit   int32
}

func (q *Queries) EntriesForOrgPage(ctx context.Context, arg EntriesForOrgPageParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, entriesForOrgPage,
		arg.OrgID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Scope,
			&i.Action,
			&i.Subject,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesForSubject = `-- name: EntriesForSubject :many
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at, org_id
from audit.entry
where subject = $1
order by occurred_at desc
limit $2
`

type EntriesForSubjectParams struct {
	Subject string
	Limit   int32
}

func (q *Queries) EntriesForSubject(ctx context.Context, arg EntriesForSubjectParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, entriesForSubject, arg.Subject, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Scope,
			&i.Action,
			&i.Subject,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesForSubjectFacetPage = `-- name: EntriesForSubjectFacetPage :many
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at, org_id
from audit.entry
where subject = $1
  and split_part(action, '.', 1) = $2
  and ($3::timestamptz is null or (occurred_at, id) < ($3::timestamptz, $4::uuid))
order by occurred_at desc, id desc
limit $5
`

type EntriesForSubjectFacetPageParams struct {
	Subject string
	Action  string
	Column3 pgtype.Timestamptz
	Column4 pgtype.UUID
	Limit   int32
}

func (q *Queries) EntriesForSubjectFacetPage(ctx context.Context, arg EntriesForSubjectFacetPageParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, entriesForSubjectFacetPage,
		arg.Subject,
		arg.Action,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Scope,
			&i.Action,
			&i.Subject,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesForSubjectPage = `-- name: EntriesForSubjectPage :many
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at, org_id
from audit.entry
where subject = $1
  and ($2::timestamptz is null or (occurred_at, id) < ($2::timestamptz, $3::uuid))
order by occurred_at desc, id desc
limit $4
`

type EntriesForSubjectPageParams struct {
	Subject string
	Column2 pgtype.Timestamptz
	Column3 pgtype.UUID
	Limit   int32
}

func (q *Queries) EntriesForSubjectPage(ctx context.Context, arg EntriesForSubjectPageParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, entriesForSubjectPage,
		arg.Subject,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Scope,
			&i.Action,
			&i.Subject,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesForWorkspace = `-- name: EntriesForWorkspace :many
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at, org_id
from audit.entry
where workspace_id = $1
order by occurred_at desc
limit $2
`

type EntriesForWorkspaceParams struct {
	WorkspaceID string
	Limit       int32
}

func (q *Queries) EntriesForWorkspace(ctx context.Context, arg EntriesForWorkspaceParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, entriesForWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Scope,
			&i.Action,
			&i.Subject,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesForWorkspaceDetailFacetPage = `-- name: EntriesForWorkspaceDetailFacetPage :many
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at, org_id
from audit.entry
where workspace_id = $1
  and detail ->> $2::text = $3::text
  and split_part(action, '.', 1) = $4::text
  and ($5::timestamptz is null or (occurred_at, id) < ($5::timestamptz, $6::uuid))
order by occurred_at desc, id desc
limit $7
`

type EntriesForWorkspaceDetailFacetPageParams struct {
	WorkspaceID string
	Column2     string
	Column3     string
	Column4     string
	Column5     pgtype.Timestamptz
	Column6     pgtype.UUID
	Limit       int32
}

func (q *Queries) EntriesForWorkspaceDetailFacetPage(ctx context.Context, arg EntriesForWorkspaceDetailFacetPageParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, entriesForWorkspaceDetailFacetPage,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Scope,
			&i.Action,
			&i.Subject,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesForWorkspaceDetailPage = `-- name: EntriesForWorkspaceDetailPage :many
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at, org_id
from audit.entry
where workspace_id = $1
  and detail ->> $2::text = $3::text
  and ($4::timestamptz is null or (occurred_at, id) < ($4::timestamptz, $5::uuid))
order by occurred_at desc, id desc
limit $6
`

type EntriesForWorkspaceDetailPageParams struct {
	WorkspaceID string
	Column2     string
	Column3     string
	Column4     pgtype.Timestamptz
	Column5     pgtype.UUID
	Limit       int32
}

func (q *Queries) EntriesForWorkspaceDetailPage(ctx context.Context, arg EntriesForWorkspaceDetailPageParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, entriesForWorkspaceDetailPage,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Scope,
			&i.Action,
			&i.Subject,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesForWorkspaceFacetPage = `-- name: EntriesForWorkspaceFacetPage :many
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at, org_id
from audit.entry
where workspace_id = $1
  and split_part(action, '.', 1) = $2
  and ($3::timestamptz is null or (occurred_at, id) < ($3::timestamptz, $4::uuid))
order by occurred_at desc, id desc
limit $5
`

type EntriesForWorkspaceFacetPageParams struct {
	WorkspaceID string
	Action      string
	Column3     pgtype.Timestamptz
	Column4     pgtype.UUID
	Limit       int32
}

func (q *Queries) EntriesForWorkspaceFacetPage(ctx context.Context, arg EntriesForWorkspaceFacetPageParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, entriesForWorkspaceFacetPage,
		arg.WorkspaceID,
		arg.Action,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Scope,
			&i.Action,
			&i.Subject,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesForWorkspacePage = `-- name: EntriesForWorkspacePage :many
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at, org_id
from audit.entry
where workspace_id = $1
  and ($2::timestamptz is null or (occurred_at, id) < ($2::timestamptz, $3::uuid))
order by occurred_at desc, id desc
limit $4
`

type EntriesForWorkspacePageParams struct {
	WorkspaceID string
	Column2     pgtype.Timestamptz
	Column3     pgtype.UUID
	Limit       int32
}

func (q *Queries) EntriesForWorkspacePage(ctx context.Context, arg EntriesForWorkspacePageParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, entriesForWorkspacePage,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Scope,
			&i.Action,
			&i.Subject,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entryByID = `-- name: EntryByID :one
select id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
       correlation_id, causation_id, detail, occurred_at, recorded_at, org_id
from audit.entry
where id = $1
`

func (q *Queries) EntryByID(ctx context.Context, id pgtype.UUID) (AuditEntry, error) {
	row := q.db.QueryRow(ctx, entryByID, id)
	var i AuditEntry
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Scope,
		&i.Action,
		&i.Subject,
		&i.Actor,
		&i.OnBehalfOf,
		&i.WorkspaceID,
		&i.CorrelationID,
		&i.CausationID,
		&i.Detail,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.OrgID,
	)
	return i, err
}

const facetsForOrg = `-- name: FacetsForOrg :many
select split_part(action, '.', 1) as facet, count(*) as total
from audit.entry
where org_id = $1
group by 1
order by 2 desc, 1
`

type FacetsForOrgRow struct {
	Facet string
	Total int64
}

func (q *Queries) FacetsForOrg(ctx context.Context, orgID string) ([]FacetsForOrgRow, error) {
	rows, err := q.db.Query(ctx, facetsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacetsForOrgRow{}
	for rows.Next() {
		var i FacetsForOrgRow
		if err := rows.Scan(&i.Facet, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facetsForSubject = `-- name: FacetsForSubject :many
select split_part(action, '.', 1) as facet, count(*) as total
from audit.entry
where subject = $1
group by 1
order by 2 desc, 1
`

type FacetsForSubjectRow struct {
	Facet string
	Total int64
}

// The action's FIRST SEGMENT, which is what the mock's facet row counts. It is
// computed rather than stored because the action is the fact and the facet is a
// reading of it: a stored column would be a second spelling that drifts the
// first time an action is renamed.
func (q *Queries) FacetsForSubject(ctx context.Context, subject string) ([]FacetsForSubjectRow, error) {
	rows, err := q.db.Query(ctx, facetsForSubject, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacetsForSubjectRow{}
	for rows.Next() {
		var i FacetsForSubjectRow
		if err := rows.Scan(&i.Facet, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facetsForWorkspace = `-- name: FacetsForWorkspace :many
select split_part(action, '.', 1) as facet, count(*) as total
from audit.entry
where workspace_id = $1
group by 1
order by 2 desc, 1
`

type FacetsForWorkspaceRow struct {
	Facet string
	Total int64
}

func (q *Queries) FacetsForWorkspace(ctx context.Context, workspaceID string) ([]FacetsForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, facetsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacetsForWorkspaceRow{}
	for rows.Next() {
		var i FacetsForWorkspaceRow
		if err := rows.Scan(&i.Facet, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facetsForWorkspaceDetail = `-- name: FacetsForWorkspaceDetail :many
select split_part(action, '.', 1) as facet, count(*) as total
from audit.entry
where workspace_id = $1
  and detail ->> $2::text = $3::text
group by 1
order by 2 desc, 1
`

type FacetsForWorkspaceDetailParams struct {
	WorkspaceID string
	Column2     string
	Column3     string
}

type FacetsForWorkspaceDetailRow struct {
	Facet string
	Total int64
}

func (q *Queries) FacetsForWorkspaceDetail(ctx context.Context, arg FacetsForWorkspaceDetailParams) ([]FacetsForWorkspaceDetailRow, error) {
	rows, err := q.db.Query(ctx, facetsForWorkspaceDetail, arg.WorkspaceID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacetsForWorkspaceDetailRow{}
	for rows.Next() {
		var i FacetsForWorkspaceDetailRow
		if err := rows.Scan(&i.Facet, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEntry = `-- name: InsertEntry :execrows
insert into audit.entry (
    id, event_id, scope, action, subject, actor, on_behalf_of, workspace_id,
    correlation_id, causation_id, detail, occurred_at, recorded_at, org_id
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
on conflict (event_id) do nothing
`

type InsertEntryParams struct {
	ID            pgtype.UUID
	EventID       pgtype.UUID
	Scope         string
	Action        string
	Subject       string
	Actor         string
	OnBehalfOf    string
	WorkspaceID   string
	CorrelationID pgtype.UUID
	CausationID   pgtype.UUID
	Detail        []byte
	OccurredAt    pgtype.Timestamptz
	RecordedAt    pgtype.Timestamptz
	OrgID         string
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEntry,
		arg.ID,
		arg.EventID,
		arg.Scope,
		arg.Action,
		arg.Subject,
		arg.Actor,
		arg.OnBehalfOf,
		arg.WorkspaceID,
		arg.CorrelationID,
		arg.CausationID,
		arg.Detail,
		arg.OccurredAt,
		arg.RecordedAt,
		arg.OrgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
