// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEntry struct {
	ID            pgtype.UUID
	EventID       pgtype.UUID
	Scope         string
	Action        string
	Subject       string
	Actor         string
	OnBehalfOf    string
	WorkspaceID   string
	CorrelationID pgtype.UUID
	CausationID   pgtype.UUID
	Detail        []byte
	OccurredAt    pgtype.Timestamptz
	RecordedAt    pgtype.Timestamptz
	OrgID         string
}
