// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package scopedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ScopeRule struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	TargetID     pgtype.UUID
	Pattern      string
	Polarity     string
	Gate         string
	Kinds        []string
	Tools        []string
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	SupersededAt pgtype.Timestamptz
	SupersededBy pgtype.UUID
}
