// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rule.sql

package scopedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allRulesForTarget = `-- name: AllRulesForTarget :many
select id, workspace_id, target_id, pattern, polarity, gate, kinds, tools,
       created_by, created_at, superseded_at, superseded_by
from scope.rule
where target_id = $1 and workspace_id = $2
order by created_at desc
`

type AllRulesForTargetParams struct {
	TargetID    pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) AllRulesForTarget(ctx context.Context, arg AllRulesForTargetParams) ([]ScopeRule, error) {
	rows, err := q.db.Query(ctx, allRulesForTarget, arg.TargetID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScopeRule{}
	for rows.Next() {
		var i ScopeRule
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TargetID,
			&i.Pattern,
			&i.Polarity,
			&i.Gate,
			&i.Kinds,
			&i.Tools,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.SupersededAt,
			&i.SupersededBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRule = `-- name: InsertRule :exec
insert into scope.rule (
    id, workspace_id, target_id, pattern, polarity, gate, kinds, tools,
    created_by, created_at, superseded_at, superseded_by
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertRuleParams struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	TargetID     pgtype.UUID
	Pattern      string
	Polarity     string
	Gate         string
	Kinds        []string
	Tools        []string
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	SupersededAt pgtype.Timestamptz
	SupersededBy pgtype.UUID
}

func (q *Queries) InsertRule(ctx context.Context, arg InsertRuleParams) error {
	_, err := q.db.Exec(ctx, insertRule,
		arg.ID,
		arg.WorkspaceID,
		arg.TargetID,
		arg.Pattern,
		arg.Polarity,
		arg.Gate,
		arg.Kinds,
		arg.Tools,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.SupersededAt,
		arg.SupersededBy,
	)
	return err
}

const liveRulesForTarget = `-- name: LiveRulesForTarget :many
select id, workspace_id, target_id, pattern, polarity, gate, kinds, tools,
       created_by, created_at, superseded_at, superseded_by
from scope.rule
where target_id = $1 and workspace_id = $2 and superseded_at is null
order by created_at
`

type LiveRulesForTargetParams struct {
	TargetID    pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) LiveRulesForTarget(ctx context.Context, arg LiveRulesForTargetParams) ([]ScopeRule, error) {
	rows, err := q.db.Query(ctx, liveRulesForTarget, arg.TargetID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScopeRule{}
	for rows.Next() {
		var i ScopeRule
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TargetID,
			&i.Pattern,
			&i.Polarity,
			&i.Gate,
			&i.Kinds,
			&i.Tools,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.SupersededAt,
			&i.SupersededBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ruleByID = `-- name: RuleByID :one
select id, workspace_id, target_id, pattern, polarity, gate, kinds, tools,
       created_by, created_at, superseded_at, superseded_by
from scope.rule where id = $1 and workspace_id = $2
`

type RuleByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

// BOTH the workspace and the id, always. The workspace is the tenancy check and
// not a filter — the same rule target's store follows.
func (q *Queries) RuleByID(ctx context.Context, arg RuleByIDParams) (ScopeRule, error) {
	row := q.db.QueryRow(ctx, ruleByID, arg.ID, arg.WorkspaceID)
	var i ScopeRule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TargetID,
		&i.Pattern,
		&i.Polarity,
		&i.Gate,
		&i.Kinds,
		&i.Tools,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.SupersededAt,
		&i.SupersededBy,
	)
	return i, err
}

const supersedeRule = `-- name: SupersedeRule :execrows
update scope.rule
set superseded_at = $3, superseded_by = $4
where id = $1 and workspace_id = $2 and superseded_at is null
`

type SupersedeRuleParams struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	SupersededAt pgtype.Timestamptz
	SupersededBy pgtype.UUID
}

// The ONLY update in this schema, and it touches the two lifecycle columns and
// nothing else — decisions/0030.
func (q *Queries) SupersedeRule(ctx context.Context, arg SupersedeRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeRule,
		arg.ID,
		arg.WorkspaceID,
		arg.SupersededAt,
		arg.SupersededBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
