// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entity.sql

package entitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assets = `-- name: Assets :many
select id, workspace_id, kind, value, origin, first_seen, last_seen, observations,
       judgement_state, judgement_by, judgement_at, judgement_reason, created_at,
       read_at, read_by,
       attribution_id, claimant, basis, root_entity_id, target_id
from entity.asset
where workspace_id = $1
  and ($2::uuid is null or target_id = $2::uuid)
order by last_seen desc nulls last, value
limit $3::int
`

type AssetsParams struct {
	WorkspaceID pgtype.UUID
	Target      pgtype.UUID
	Page        int32
}

// Reads the VIEW, which is the point of the view: the word and the query are the
// same object — 0009.
func (q *Queries) Assets(ctx context.Context, arg AssetsParams) ([]EntityAsset, error) {
	rows, err := q.db.Query(ctx, assets, arg.WorkspaceID, arg.Target, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityAsset{}
	for rows.Next() {
		var i EntityAsset
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Value,
			&i.Origin,
			&i.FirstSeen,
			&i.LastSeen,
			&i.Observations,
			&i.JudgementState,
			&i.JudgementBy,
			&i.JudgementAt,
			&i.JudgementReason,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ReadBy,
			&i.AttributionID,
			&i.Claimant,
			&i.Basis,
			&i.RootEntityID,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attributionByID = `-- name: AttributionByID :one
select id, workspace_id, entity_id, fragment_id, claimant, claimant_ref,
       confidence, basis, state, decided_at, decided_by, decided_note, created_at
from entity.attribution where id = $1 and workspace_id = $2
`

type AttributionByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) AttributionByID(ctx context.Context, arg AttributionByIDParams) (EntityAttribution, error) {
	row := q.db.QueryRow(ctx, attributionByID, arg.ID, arg.WorkspaceID)
	var i EntityAttribution
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityID,
		&i.FragmentID,
		&i.Claimant,
		&i.ClaimantRef,
		&i.Confidence,
		&i.Basis,
		&i.State,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.DecidedNote,
		&i.CreatedAt,
	)
	return i, err
}

const attributionsForEntity = `-- name: AttributionsForEntity :many
select id, workspace_id, entity_id, fragment_id, claimant, claimant_ref,
       confidence, basis, state, decided_at, decided_by, decided_note, created_at
from entity.attribution
where entity_id = $1
  and ($2::text is null or state = $2::text)
order by created_at
limit $3::int
`

type AttributionsForEntityParams struct {
	EntityID pgtype.UUID
	State    pgtype.Text
	Page     int32
}

func (q *Queries) AttributionsForEntity(ctx context.Context, arg AttributionsForEntityParams) ([]EntityAttribution, error) {
	rows, err := q.db.Query(ctx, attributionsForEntity, arg.EntityID, arg.State, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityAttribution{}
	for rows.Next() {
		var i EntityAttribution
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityID,
			&i.FragmentID,
			&i.Claimant,
			&i.ClaimantRef,
			&i.Confidence,
			&i.Basis,
			&i.State,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.DecidedNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attributionsForFragment = `-- name: AttributionsForFragment :many
select id, workspace_id, entity_id, fragment_id, claimant, claimant_ref,
       confidence, basis, state, decided_at, decided_by, decided_note, created_at
from entity.attribution where fragment_id = $1 order by created_at
`

func (q *Queries) AttributionsForFragment(ctx context.Context, fragmentID pgtype.UUID) ([]EntityAttribution, error) {
	rows, err := q.db.Query(ctx, attributionsForFragment, fragmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityAttribution{}
	for rows.Next() {
		var i EntityAttribution
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityID,
			&i.FragmentID,
			&i.Claimant,
			&i.ClaimantRef,
			&i.Confidence,
			&i.Basis,
			&i.State,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.DecidedNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const decideAttribution = `-- name: DecideAttribution :execrows
update entity.attribution
set state = $3, decided_at = $4, decided_by = $5, decided_note = $6
where id = $1 and workspace_id = $2 and state = 'proposed'
`

type DecideAttributionParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	State       string
	DecidedAt   pgtype.Timestamptz
	DecidedBy   pgtype.UUID
	DecidedNote pgtype.Text
}

// It never touches `claimant` — 0008's title — and the predicate refuses a
// second ruling, so two people accepting at once produce one winner.
func (q *Queries) DecideAttribution(ctx context.Context, arg DecideAttributionParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideAttribution,
		arg.ID,
		arg.WorkspaceID,
		arg.State,
		arg.DecidedAt,
		arg.DecidedBy,
		arg.DecidedNote,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const entitiesForWorkspace = `-- name: EntitiesForWorkspace :many
select id, workspace_id, kind, label, target_id,
       judgement_state, judgement_by, judgement_at, judgement_reason, created_at
from entity.entity where workspace_id = $1 order by created_at
limit $2::int
`

type EntitiesForWorkspaceParams struct {
	WorkspaceID pgtype.UUID
	Page        int32
}

func (q *Queries) EntitiesForWorkspace(ctx context.Context, arg EntitiesForWorkspaceParams) ([]EntityEntity, error) {
	rows, err := q.db.Query(ctx, entitiesForWorkspace, arg.WorkspaceID, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityEntity{}
	for rows.Next() {
		var i EntityEntity
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Label,
			&i.TargetID,
			&i.JudgementState,
			&i.JudgementBy,
			&i.JudgementAt,
			&i.JudgementReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entityByID = `-- name: EntityByID :one
select id, workspace_id, kind, label, target_id,
       judgement_state, judgement_by, judgement_at, judgement_reason, created_at
from entity.entity where id = $1 and workspace_id = $2
`

type EntityByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) EntityByID(ctx context.Context, arg EntityByIDParams) (EntityEntity, error) {
	row := q.db.QueryRow(ctx, entityByID, arg.ID, arg.WorkspaceID)
	var i EntityEntity
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Label,
		&i.TargetID,
		&i.JudgementState,
		&i.JudgementBy,
		&i.JudgementAt,
		&i.JudgementReason,
		&i.CreatedAt,
	)
	return i, err
}

const fragmentByID = `-- name: FragmentByID :one
select id, workspace_id, kind, value, origin, first_seen, last_seen,
       observations, judgement_state, judgement_by, judgement_at,
       judgement_reason, created_at, read_at, read_by
from entity.fragment where id = $1 and workspace_id = $2
`

type FragmentByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) FragmentByID(ctx context.Context, arg FragmentByIDParams) (EntityFragment, error) {
	row := q.db.QueryRow(ctx, fragmentByID, arg.ID, arg.WorkspaceID)
	var i EntityFragment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Value,
		&i.Origin,
		&i.FirstSeen,
		&i.LastSeen,
		&i.Observations,
		&i.JudgementState,
		&i.JudgementBy,
		&i.JudgementAt,
		&i.JudgementReason,
		&i.CreatedAt,
		&i.ReadAt,
		&i.ReadBy,
	)
	return i, err
}

const fragmentsForWorkspace = `-- name: FragmentsForWorkspace :many
select id, workspace_id, kind, value, origin, first_seen, last_seen,
       observations, judgement_state, judgement_by, judgement_at,
       judgement_reason, created_at, read_at, read_by
from entity.fragment
where workspace_id = $1
  and ($2::text is null or kind = $2::text)
order by last_seen desc nulls last, value
limit $3::int
`

type FragmentsForWorkspaceParams struct {
	WorkspaceID pgtype.UUID
	Kind        pgtype.Text
	Page        int32
}

func (q *Queries) FragmentsForWorkspace(ctx context.Context, arg FragmentsForWorkspaceParams) ([]EntityFragment, error) {
	rows, err := q.db.Query(ctx, fragmentsForWorkspace, arg.WorkspaceID, arg.Kind, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityFragment{}
	for rows.Next() {
		var i EntityFragment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Value,
			&i.Origin,
			&i.FirstSeen,
			&i.LastSeen,
			&i.Observations,
			&i.JudgementState,
			&i.JudgementBy,
			&i.JudgementAt,
			&i.JudgementReason,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ReadBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAttribution = `-- name: InsertAttribution :exec
insert into entity.attribution (
    id, workspace_id, entity_id, fragment_id, claimant, claimant_ref,
    confidence, basis, state, decided_at, decided_by, decided_note, created_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
on conflict (entity_id, fragment_id) do nothing
`

type InsertAttributionParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	EntityID    pgtype.UUID
	FragmentID  pgtype.UUID
	Claimant    string
	ClaimantRef pgtype.UUID
	Confidence  pgtype.Float8
	Basis       string
	State       string
	DecidedAt   pgtype.Timestamptz
	DecidedBy   pgtype.UUID
	DecidedNote pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

// One claim per (entity, fragment), and a redelivered subscriber event must not
// write a second.
func (q *Queries) InsertAttribution(ctx context.Context, arg InsertAttributionParams) error {
	_, err := q.db.Exec(ctx, insertAttribution,
		arg.ID,
		arg.WorkspaceID,
		arg.EntityID,
		arg.FragmentID,
		arg.Claimant,
		arg.ClaimantRef,
		arg.Confidence,
		arg.Basis,
		arg.State,
		arg.DecidedAt,
		arg.DecidedBy,
		arg.DecidedNote,
		arg.CreatedAt,
	)
	return err
}

const insertEntity = `-- name: InsertEntity :exec
insert into entity.entity (
    id, workspace_id, kind, label, target_id,
    judgement_state, judgement_by, judgement_at, judgement_reason, created_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
on conflict do nothing
`

type InsertEntityParams struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	Kind            string
	Label           string
	TargetID        pgtype.UUID
	JudgementState  string
	JudgementBy     pgtype.UUID
	JudgementAt     pgtype.Timestamptz
	JudgementReason pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

// IDEMPOTENT ON REDELIVERY. `entity_one_root_per_target` refuses a second root
// and the outbox delivers at least once, so a redelivered `target.added` must be
// a no-op rather than an error — decisions/0007.
func (q *Queries) InsertEntity(ctx context.Context, arg InsertEntityParams) error {
	_, err := q.db.Exec(ctx, insertEntity,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Label,
		arg.TargetID,
		arg.JudgementState,
		arg.JudgementBy,
		arg.JudgementAt,
		arg.JudgementReason,
		arg.CreatedAt,
	)
	return err
}

const judgeEntity = `-- name: JudgeEntity :execrows
update entity.entity
set judgement_state = $3, judgement_by = $4, judgement_at = $5, judgement_reason = $6
where id = $1 and workspace_id = $2
`

type JudgeEntityParams struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	JudgementState  string
	JudgementBy     pgtype.UUID
	JudgementAt     pgtype.Timestamptz
	JudgementReason pgtype.Text
}

func (q *Queries) JudgeEntity(ctx context.Context, arg JudgeEntityParams) (int64, error) {
	result, err := q.db.Exec(ctx, judgeEntity,
		arg.ID,
		arg.WorkspaceID,
		arg.JudgementState,
		arg.JudgementBy,
		arg.JudgementAt,
		arg.JudgementReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const judgeFragment = `-- name: JudgeFragment :execrows
update entity.fragment
set judgement_state = $3, judgement_by = $4, judgement_at = $5, judgement_reason = $6
where id = $1 and workspace_id = $2
`

type JudgeFragmentParams struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	JudgementState  string
	JudgementBy     pgtype.UUID
	JudgementAt     pgtype.Timestamptz
	JudgementReason pgtype.Text
}

func (q *Queries) JudgeFragment(ctx context.Context, arg JudgeFragmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, judgeFragment,
		arg.ID,
		arg.WorkspaceID,
		arg.JudgementState,
		arg.JudgementBy,
		arg.JudgementAt,
		arg.JudgementReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRead = `-- name: MarkRead :execrows
update entity.fragment
set read_at = $3, read_by = $4
where id = $1 and workspace_id = $2
`

type MarkReadParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	ReadAt      pgtype.Timestamptz
	ReadBy      pgtype.UUID
}

// A READ, not a ruling — decisions/0037. It deliberately does not touch the
// judgement columns: reading is not ruling, and a client that wants both makes
// two calls because they are two acts.
func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRead,
		arg.ID,
		arg.WorkspaceID,
		arg.ReadAt,
		arg.ReadBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rootEntityForTarget = `-- name: RootEntityForTarget :one
select id, workspace_id, kind, label, target_id,
       judgement_state, judgement_by, judgement_at, judgement_reason, created_at
from entity.entity where target_id = $1
`

func (q *Queries) RootEntityForTarget(ctx context.Context, targetID pgtype.UUID) (EntityEntity, error) {
	row := q.db.QueryRow(ctx, rootEntityForTarget, targetID)
	var i EntityEntity
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Label,
		&i.TargetID,
		&i.JudgementState,
		&i.JudgementBy,
		&i.JudgementAt,
		&i.JudgementReason,
		&i.CreatedAt,
	)
	return i, err
}

const upsertFragment = `-- name: UpsertFragment :one
insert into entity.fragment (
    id, workspace_id, kind, value, origin, first_seen, last_seen, observations, created_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict (workspace_id, kind, value) do update
set observations = entity.fragment.observations + excluded.observations,
    first_seen   = least(entity.fragment.first_seen, excluded.first_seen),
    last_seen    = greatest(entity.fragment.last_seen, excluded.last_seen),
    origin       = case when excluded.origin = 'observed' then 'observed'
                        else entity.fragment.origin end
returning id, workspace_id, kind, value, origin, first_seen, last_seen,
          observations, judgement_state, judgement_by, judgement_at,
          judgement_reason, created_at, read_at, read_by, (xmax = 0) as inserted
`

type UpsertFragmentParams struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	Kind         string
	Value        string
	Origin       string
	FirstSeen    pgtype.Timestamptz
	LastSeen     pgtype.Timestamptz
	Observations int32
	CreatedAt    pgtype.Timestamptz
}

type UpsertFragmentRow struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	Kind            string
	Value           string
	Origin          string
	FirstSeen       pgtype.Timestamptz
	LastSeen        pgtype.Timestamptz
	Observations    int32
	JudgementState  string
	JudgementBy     pgtype.UUID
	JudgementAt     pgtype.Timestamptz
	JudgementReason pgtype.Text
	CreatedAt       pgtype.Timestamptz
	ReadAt          pgtype.Timestamptz
	ReadBy          pgtype.UUID
	Inserted        bool
}

// THE DEDUP, as one statement — decisions/0036. A fragment IS the tuple, so the
// conflict target is the tuple.
//
// `last_seen` uses greatest() and `first_seen` least(), so a re-extraction of an
// old artifact moves neither in the wrong direction. `observations` ADDS,
// because two statements about one fragment are two statements.
//
// ORIGIN is promoted, never demoted: a manual fragment a tool later finds
// becomes observed, which is a stronger claim than either alone. `least()` over
// the text does that by luck of the alphabet, so it is spelled out instead.
func (q *Queries) UpsertFragment(ctx context.Context, arg UpsertFragmentParams) (UpsertFragmentRow, error) {
	row := q.db.QueryRow(ctx, upsertFragment,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Value,
		arg.Origin,
		arg.FirstSeen,
		arg.LastSeen,
		arg.Observations,
		arg.CreatedAt,
	)
	var i UpsertFragmentRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Value,
		&i.Origin,
		&i.FirstSeen,
		&i.LastSeen,
		&i.Observations,
		&i.JudgementState,
		&i.JudgementBy,
		&i.JudgementAt,
		&i.JudgementReason,
		&i.CreatedAt,
		&i.ReadAt,
		&i.ReadBy,
		&i.Inserted,
	)
	return i, err
}
