// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entity.sql

package entitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptedFragmentsForTarget = `-- name: AcceptedFragmentsForTarget :many
select distinct a.fragment_id
from entity.attribution a
join entity.entity e on e.id = a.entity_id and e.workspace_id = a.workspace_id
join entity.fragment f on f.id = a.fragment_id and f.workspace_id = a.workspace_id
where a.workspace_id = $1 and e.target_id = $2 and a.state = 'accepted'
order by a.fragment_id
`

type AcceptedFragmentsForTargetParams struct {
	WorkspaceID pgtype.UUID
	TargetID    pgtype.UUID
}

// Includes non-asset kinds, such as documents, while retaining target and
// workspace isolation. Proposed and rejected connections supply no attribution.
func (q *Queries) AcceptedFragmentsForTarget(ctx context.Context, arg AcceptedFragmentsForTargetParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, acceptedFragmentsForTarget, arg.WorkspaceID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var fragment_id pgtype.UUID
		if err := rows.Scan(&fragment_id); err != nil {
			return nil, err
		}
		items = append(items, fragment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allAssets = `-- name: AllAssets :many
select id, workspace_id, kind, value, origin, first_seen, last_seen, observations,
       judgement_state, judgement_by, judgement_at, judgement_reason, created_at,
       read_at, read_by,
       attribution_id, claimant, basis, root_entity_id, target_id
from entity.asset
where workspace_id = $1
  and ($2::uuid is null or target_id = $2::uuid)
order by last_seen desc nulls last, value
`

type AllAssetsParams struct {
	WorkspaceID pgtype.UUID
	Target      pgtype.UUID
}

// Reads the VIEW, which is the point of the view: the word and the query are the
// same object — 0009.
func (q *Queries) AllAssets(ctx context.Context, arg AllAssetsParams) ([]EntityAsset, error) {
	rows, err := q.db.Query(ctx, allAssets, arg.WorkspaceID, arg.Target)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityAsset{}
	for rows.Next() {
		var i EntityAsset
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Value,
			&i.Origin,
			&i.FirstSeen,
			&i.LastSeen,
			&i.Observations,
			&i.JudgementState,
			&i.JudgementBy,
			&i.JudgementAt,
			&i.JudgementReason,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ReadBy,
			&i.AttributionID,
			&i.Claimant,
			&i.Basis,
			&i.RootEntityID,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assets = `-- name: Assets :many
select id, workspace_id, kind, value, origin, first_seen, last_seen, observations,
       judgement_state, judgement_by, judgement_at, judgement_reason, created_at,
       read_at, read_by,
       attribution_id, claimant, basis, root_entity_id, target_id
from entity.asset
where workspace_id = $1
  and ($2::uuid is null or target_id = $2::uuid)
order by last_seen desc nulls last, value
limit $3::int
`

type AssetsParams struct {
	WorkspaceID pgtype.UUID
	Target      pgtype.UUID
	Page        int32
}

// Reads the VIEW, which is the point of the view: the word and the query are the
// same object — 0009.
func (q *Queries) Assets(ctx context.Context, arg AssetsParams) ([]EntityAsset, error) {
	rows, err := q.db.Query(ctx, assets, arg.WorkspaceID, arg.Target, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityAsset{}
	for rows.Next() {
		var i EntityAsset
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Value,
			&i.Origin,
			&i.FirstSeen,
			&i.LastSeen,
			&i.Observations,
			&i.JudgementState,
			&i.JudgementBy,
			&i.JudgementAt,
			&i.JudgementReason,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ReadBy,
			&i.AttributionID,
			&i.Claimant,
			&i.Basis,
			&i.RootEntityID,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attributionByID = `-- name: AttributionByID :one
select id, workspace_id, entity_id, fragment_id, claimant, claimant_ref,
       confidence, basis, state, decided_at, decided_by, decided_note, created_at
from entity.attribution where id = $1 and workspace_id = $2
`

type AttributionByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) AttributionByID(ctx context.Context, arg AttributionByIDParams) (EntityAttribution, error) {
	row := q.db.QueryRow(ctx, attributionByID, arg.ID, arg.WorkspaceID)
	var i EntityAttribution
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityID,
		&i.FragmentID,
		&i.Claimant,
		&i.ClaimantRef,
		&i.Confidence,
		&i.Basis,
		&i.State,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.DecidedNote,
		&i.CreatedAt,
	)
	return i, err
}

const attributionsForEntity = `-- name: AttributionsForEntity :many
select id, workspace_id, entity_id, fragment_id, claimant, claimant_ref,
       confidence, basis, state, decided_at, decided_by, decided_note, created_at
from entity.attribution
where entity_id = $1
  and ($2::text is null or state = $2::text)
order by created_at
limit $3::int
`

type AttributionsForEntityParams struct {
	EntityID pgtype.UUID
	State    pgtype.Text
	Page     int32
}

func (q *Queries) AttributionsForEntity(ctx context.Context, arg AttributionsForEntityParams) ([]EntityAttribution, error) {
	rows, err := q.db.Query(ctx, attributionsForEntity, arg.EntityID, arg.State, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityAttribution{}
	for rows.Next() {
		var i EntityAttribution
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityID,
			&i.FragmentID,
			&i.Claimant,
			&i.ClaimantRef,
			&i.Confidence,
			&i.Basis,
			&i.State,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.DecidedNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attributionsForFragment = `-- name: AttributionsForFragment :many
select id, workspace_id, entity_id, fragment_id, claimant, claimant_ref,
       confidence, basis, state, decided_at, decided_by, decided_note, created_at
from entity.attribution where fragment_id = $1 order by created_at
`

func (q *Queries) AttributionsForFragment(ctx context.Context, fragmentID pgtype.UUID) ([]EntityAttribution, error) {
	rows, err := q.db.Query(ctx, attributionsForFragment, fragmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityAttribution{}
	for rows.Next() {
		var i EntityAttribution
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityID,
			&i.FragmentID,
			&i.Claimant,
			&i.ClaimantRef,
			&i.Confidence,
			&i.Basis,
			&i.State,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.DecidedNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const decideAttribution = `-- name: DecideAttribution :execrows
update entity.attribution
set state = $3, decided_at = $4, decided_by = $5, decided_note = $6
where id = $1 and workspace_id = $2 and state = 'proposed'
`

type DecideAttributionParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	State       string
	DecidedAt   pgtype.Timestamptz
	DecidedBy   pgtype.UUID
	DecidedNote pgtype.Text
}

// It never touches `claimant` — 0008's title — and the predicate refuses a
// second ruling, so two people accepting at once produce one winner.
func (q *Queries) DecideAttribution(ctx context.Context, arg DecideAttributionParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideAttribution,
		arg.ID,
		arg.WorkspaceID,
		arg.State,
		arg.DecidedAt,
		arg.DecidedBy,
		arg.DecidedNote,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const derivationsAmong = `-- name: DerivationsAmong :many
select id, workspace_id, from_fragment_id, to_fragment_id, label,
       invocation_id, artifact_id, mapping_id, created_at
from entity.derivation
where workspace_id = $1
  and from_fragment_id = any($2::uuid[])
  and to_fragment_id = any($2::uuid[])
order by created_at
`

type DerivationsAmongParams struct {
	WorkspaceID pgtype.UUID
	Fragments   []pgtype.UUID
}

// Every edge BETWEEN THESE FRAGMENTS — decisions/0044 §1. Both ends must be on
// the canvas: drawing an edge to a node that is not there implies the picture is
// complete and the reader cannot see why the line stops.
func (q *Queries) DerivationsAmong(ctx context.Context, arg DerivationsAmongParams) ([]EntityDerivation, error) {
	rows, err := q.db.Query(ctx, derivationsAmong, arg.WorkspaceID, arg.Fragments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityDerivation{}
	for rows.Next() {
		var i EntityDerivation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FromFragmentID,
			&i.ToFragmentID,
			&i.Label,
			&i.InvocationID,
			&i.ArtifactID,
			&i.MappingID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const derivationsForFragment = `-- name: DerivationsForFragment :many
select id, workspace_id, from_fragment_id, to_fragment_id, label,
       invocation_id, artifact_id, mapping_id, created_at
from entity.derivation
where workspace_id = $1 and (from_fragment_id = $2 or to_fragment_id = $2)
order by created_at desc
limit $3::int
`

type DerivationsForFragmentParams struct {
	WorkspaceID    pgtype.UUID
	FromFragmentID pgtype.UUID
	Page           int32
}

// BOTH DIRECTIONS in one read. The canvas draws outward from a fragment and
// does not care which end it is; two queries would make the caller union them
// and get the ordering wrong.
func (q *Queries) DerivationsForFragment(ctx context.Context, arg DerivationsForFragmentParams) ([]EntityDerivation, error) {
	rows, err := q.db.Query(ctx, derivationsForFragment, arg.WorkspaceID, arg.FromFragmentID, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityDerivation{}
	for rows.Next() {
		var i EntityDerivation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FromFragmentID,
			&i.ToFragmentID,
			&i.Label,
			&i.InvocationID,
			&i.ArtifactID,
			&i.MappingID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entitiesForWorkspace = `-- name: EntitiesForWorkspace :many
select id, workspace_id, kind, label, target_id,
       judgement_state, judgement_by, judgement_at, judgement_reason, created_at
from entity.entity where workspace_id = $1 order by created_at
limit $2::int
`

type EntitiesForWorkspaceParams struct {
	WorkspaceID pgtype.UUID
	Page        int32
}

func (q *Queries) EntitiesForWorkspace(ctx context.Context, arg EntitiesForWorkspaceParams) ([]EntityEntity, error) {
	rows, err := q.db.Query(ctx, entitiesForWorkspace, arg.WorkspaceID, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityEntity{}
	for rows.Next() {
		var i EntityEntity
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Label,
			&i.TargetID,
			&i.JudgementState,
			&i.JudgementBy,
			&i.JudgementAt,
			&i.JudgementReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entityByID = `-- name: EntityByID :one
select id, workspace_id, kind, label, target_id,
       judgement_state, judgement_by, judgement_at, judgement_reason, created_at
from entity.entity where id = $1 and workspace_id = $2
`

type EntityByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) EntityByID(ctx context.Context, arg EntityByIDParams) (EntityEntity, error) {
	row := q.db.QueryRow(ctx, entityByID, arg.ID, arg.WorkspaceID)
	var i EntityEntity
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Label,
		&i.TargetID,
		&i.JudgementState,
		&i.JudgementBy,
		&i.JudgementAt,
		&i.JudgementReason,
		&i.CreatedAt,
	)
	return i, err
}

const fragmentByID = `-- name: FragmentByID :one
select id, workspace_id, kind, value, origin, first_seen, last_seen,
       observations, judgement_state, judgement_by, judgement_at,
       judgement_reason, created_at, read_at, read_by
from entity.fragment where id = $1 and workspace_id = $2
`

type FragmentByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) FragmentByID(ctx context.Context, arg FragmentByIDParams) (EntityFragment, error) {
	row := q.db.QueryRow(ctx, fragmentByID, arg.ID, arg.WorkspaceID)
	var i EntityFragment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Value,
		&i.Origin,
		&i.FirstSeen,
		&i.LastSeen,
		&i.Observations,
		&i.JudgementState,
		&i.JudgementBy,
		&i.JudgementAt,
		&i.JudgementReason,
		&i.CreatedAt,
		&i.ReadAt,
		&i.ReadBy,
	)
	return i, err
}

const fragmentForValue = `-- name: FragmentForValue :one
select id, workspace_id, kind, value, origin, first_seen, last_seen,
       observations, judgement_state, judgement_by, judgement_at,
       judgement_reason, created_at, read_at, read_by
from entity.fragment where workspace_id = $1 and kind = $2 and value = $3
`

type FragmentForValueParams struct {
	WorkspaceID pgtype.UUID
	Kind        string
	Value       string
}

// THE LOOKUP A DERIVATION'S `from` RESOLVES THROUGH — decisions/0040 §5.
//
// The value is folded by the ADAPTER, not by the caller and not here. The
// column is folded, `entity.domain.Fold` is the one function that decides what
// "the same host" means, and the store is the single door every lookup goes
// through — so a caller cannot forget, and there is no `lower()` here competing
// with a Go function for the definition.
func (q *Queries) FragmentForValue(ctx context.Context, arg FragmentForValueParams) (EntityFragment, error) {
	row := q.db.QueryRow(ctx, fragmentForValue, arg.WorkspaceID, arg.Kind, arg.Value)
	var i EntityFragment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Value,
		&i.Origin,
		&i.FirstSeen,
		&i.LastSeen,
		&i.Observations,
		&i.JudgementState,
		&i.JudgementBy,
		&i.JudgementAt,
		&i.JudgementReason,
		&i.CreatedAt,
		&i.ReadAt,
		&i.ReadBy,
	)
	return i, err
}

const fragmentsForWorkspace = `-- name: FragmentsForWorkspace :many
select id, workspace_id, kind, value, origin, first_seen, last_seen,
       observations, judgement_state, judgement_by, judgement_at,
       judgement_reason, created_at, read_at, read_by
from entity.fragment
where workspace_id = $1
  and ($2::text is null or kind = $2::text)
order by last_seen desc nulls last, value
limit $3::int
`

type FragmentsForWorkspaceParams struct {
	WorkspaceID pgtype.UUID
	Kind        pgtype.Text
	Page        int32
}

func (q *Queries) FragmentsForWorkspace(ctx context.Context, arg FragmentsForWorkspaceParams) ([]EntityFragment, error) {
	rows, err := q.db.Query(ctx, fragmentsForWorkspace, arg.WorkspaceID, arg.Kind, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityFragment{}
	for rows.Next() {
		var i EntityFragment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Value,
			&i.Origin,
			&i.FirstSeen,
			&i.LastSeen,
			&i.Observations,
			&i.JudgementState,
			&i.JudgementBy,
			&i.JudgementAt,
			&i.JudgementReason,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ReadBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAttribution = `-- name: InsertAttribution :exec
insert into entity.attribution (
    id, workspace_id, entity_id, fragment_id, claimant, claimant_ref,
    confidence, basis, state, decided_at, decided_by, decided_note, created_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
on conflict (entity_id, fragment_id) do nothing
`

type InsertAttributionParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	EntityID    pgtype.UUID
	FragmentID  pgtype.UUID
	Claimant    string
	ClaimantRef pgtype.UUID
	Confidence  pgtype.Float8
	Basis       string
	State       string
	DecidedAt   pgtype.Timestamptz
	DecidedBy   pgtype.UUID
	DecidedNote pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

// One claim per (entity, fragment), and a redelivered subscriber event must not
// write a second.
func (q *Queries) InsertAttribution(ctx context.Context, arg InsertAttributionParams) error {
	_, err := q.db.Exec(ctx, insertAttribution,
		arg.ID,
		arg.WorkspaceID,
		arg.EntityID,
		arg.FragmentID,
		arg.Claimant,
		arg.ClaimantRef,
		arg.Confidence,
		arg.Basis,
		arg.State,
		arg.DecidedAt,
		arg.DecidedBy,
		arg.DecidedNote,
		arg.CreatedAt,
	)
	return err
}

const insertDerivation = `-- name: InsertDerivation :exec
insert into entity.derivation (
    id, workspace_id, from_fragment_id, to_fragment_id, label,
    invocation_id, artifact_id, mapping_id, created_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict (from_fragment_id, to_fragment_id, label, invocation_id) do nothing
`

type InsertDerivationParams struct {
	ID             pgtype.UUID
	WorkspaceID    pgtype.UUID
	FromFragmentID pgtype.UUID
	ToFragmentID   pgtype.UUID
	Label          string
	InvocationID   pgtype.UUID
	ArtifactID     pgtype.UUID
	MappingID      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

// `0003`'s second edge kind. ON CONFLICT DO NOTHING against `derivation_once`:
// the outbox is at-least-once (0007) and a redelivered extraction must not
// double the graph.
func (q *Queries) InsertDerivation(ctx context.Context, arg InsertDerivationParams) error {
	_, err := q.db.Exec(ctx, insertDerivation,
		arg.ID,
		arg.WorkspaceID,
		arg.FromFragmentID,
		arg.ToFragmentID,
		arg.Label,
		arg.InvocationID,
		arg.ArtifactID,
		arg.MappingID,
		arg.CreatedAt,
	)
	return err
}

const insertEntity = `-- name: InsertEntity :exec
insert into entity.entity (
    id, workspace_id, kind, label, target_id,
    judgement_state, judgement_by, judgement_at, judgement_reason, created_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
on conflict do nothing
`

type InsertEntityParams struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	Kind            string
	Label           string
	TargetID        pgtype.UUID
	JudgementState  string
	JudgementBy     pgtype.UUID
	JudgementAt     pgtype.Timestamptz
	JudgementReason pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

// IDEMPOTENT ON REDELIVERY. `entity_one_root_per_target` refuses a second root
// and the outbox delivers at least once, so a redelivered `target.added` must be
// a no-op rather than an error — decisions/0007.
func (q *Queries) InsertEntity(ctx context.Context, arg InsertEntityParams) error {
	_, err := q.db.Exec(ctx, insertEntity,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Label,
		arg.TargetID,
		arg.JudgementState,
		arg.JudgementBy,
		arg.JudgementAt,
		arg.JudgementReason,
		arg.CreatedAt,
	)
	return err
}

const insertUnresolved = `-- name: InsertUnresolved :exec
insert into entity.derivation_unresolved (
    id, workspace_id, invocation_id, mapping_id, to_fragment_id,
    from_kind, from_value, from_raw, label, created_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
on conflict (invocation_id, to_fragment_id, from_value, label) do nothing
`

type InsertUnresolvedParams struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	InvocationID pgtype.UUID
	MappingID    pgtype.UUID
	ToFragmentID pgtype.UUID
	FromKind     string
	FromValue    string
	FromRaw      string
	Label        string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertUnresolved(ctx context.Context, arg InsertUnresolvedParams) error {
	_, err := q.db.Exec(ctx, insertUnresolved,
		arg.ID,
		arg.WorkspaceID,
		arg.InvocationID,
		arg.MappingID,
		arg.ToFragmentID,
		arg.FromKind,
		arg.FromValue,
		arg.FromRaw,
		arg.Label,
		arg.CreatedAt,
	)
	return err
}

const judgeEntity = `-- name: JudgeEntity :execrows
update entity.entity
set judgement_state = $3, judgement_by = $4, judgement_at = $5, judgement_reason = $6
where id = $1 and workspace_id = $2
`

type JudgeEntityParams struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	JudgementState  string
	JudgementBy     pgtype.UUID
	JudgementAt     pgtype.Timestamptz
	JudgementReason pgtype.Text
}

func (q *Queries) JudgeEntity(ctx context.Context, arg JudgeEntityParams) (int64, error) {
	result, err := q.db.Exec(ctx, judgeEntity,
		arg.ID,
		arg.WorkspaceID,
		arg.JudgementState,
		arg.JudgementBy,
		arg.JudgementAt,
		arg.JudgementReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const judgeFragment = `-- name: JudgeFragment :execrows
update entity.fragment
set judgement_state = $3, judgement_by = $4, judgement_at = $5, judgement_reason = $6
where id = $1 and workspace_id = $2
`

type JudgeFragmentParams struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	JudgementState  string
	JudgementBy     pgtype.UUID
	JudgementAt     pgtype.Timestamptz
	JudgementReason pgtype.Text
}

func (q *Queries) JudgeFragment(ctx context.Context, arg JudgeFragmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, judgeFragment,
		arg.ID,
		arg.WorkspaceID,
		arg.JudgementState,
		arg.JudgementBy,
		arg.JudgementAt,
		arg.JudgementReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRead = `-- name: MarkRead :execrows
update entity.fragment
set read_at = $3, read_by = $4
where id = $1 and workspace_id = $2
`

type MarkReadParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	ReadAt      pgtype.Timestamptz
	ReadBy      pgtype.UUID
}

// A READ, not a ruling — decisions/0037. It deliberately does not touch the
// judgement columns: reading is not ruling, and a client that wants both makes
// two calls because they are two acts.
func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRead,
		arg.ID,
		arg.WorkspaceID,
		arg.ReadAt,
		arg.ReadBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rootEntityForTarget = `-- name: RootEntityForTarget :one
select id, workspace_id, kind, label, target_id,
       judgement_state, judgement_by, judgement_at, judgement_reason, created_at
from entity.entity where target_id = $1
`

func (q *Queries) RootEntityForTarget(ctx context.Context, targetID pgtype.UUID) (EntityEntity, error) {
	row := q.db.QueryRow(ctx, rootEntityForTarget, targetID)
	var i EntityEntity
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Label,
		&i.TargetID,
		&i.JudgementState,
		&i.JudgementBy,
		&i.JudgementAt,
		&i.JudgementReason,
		&i.CreatedAt,
	)
	return i, err
}

const rootsPerFragment = `-- name: RootsPerFragment :many
select fragment_id, count(distinct entity_id)::int as roots
from entity.attribution
where workspace_id = $1
  and state = 'accepted'
  and fragment_id = any($2::uuid[])
group by fragment_id
`

type RootsPerFragmentParams struct {
	WorkspaceID pgtype.UUID
	Fragments   []pgtype.UUID
}

type RootsPerFragmentRow struct {
	FragmentID pgtype.UUID
	Roots      int32
}

// How many DISTINCT ROOT ENTITIES have an accepted attribution to each of these
// fragments — decisions/0044 §2's `seen elsewhere`.
//
// **WITHIN ONE WORKSPACE, and it cannot be otherwise.** `entity.fragment` is
// (workspace, kind, value), so a fragment does not exist across engagements at
// all; what this finds is one client's two subsidiaries sharing a host.
//
// Crossing a workspace was refused in 0044 §2 and the reason is a disclosure:
// an analyst on one engagement holding `none` on another must not learn that
// other engagement exists.
func (q *Queries) RootsPerFragment(ctx context.Context, arg RootsPerFragmentParams) ([]RootsPerFragmentRow, error) {
	rows, err := q.db.Query(ctx, rootsPerFragment, arg.WorkspaceID, arg.Fragments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RootsPerFragmentRow{}
	for rows.Next() {
		var i RootsPerFragmentRow
		if err := rows.Scan(&i.FragmentID, &i.Roots); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unresolvedForInvocation = `-- name: UnresolvedForInvocation :many
select id, workspace_id, invocation_id, mapping_id, to_fragment_id,
       from_kind, from_value, from_raw, label, created_at
from entity.derivation_unresolved
where workspace_id = $1 and invocation_id = $2
order by from_value
`

type UnresolvedForInvocationParams struct {
	WorkspaceID  pgtype.UUID
	InvocationID pgtype.UUID
}

func (q *Queries) UnresolvedForInvocation(ctx context.Context, arg UnresolvedForInvocationParams) ([]EntityDerivationUnresolved, error) {
	rows, err := q.db.Query(ctx, unresolvedForInvocation, arg.WorkspaceID, arg.InvocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityDerivationUnresolved{}
	for rows.Next() {
		var i EntityDerivationUnresolved
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InvocationID,
			&i.MappingID,
			&i.ToFragmentID,
			&i.FromKind,
			&i.FromValue,
			&i.FromRaw,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFragment = `-- name: UpsertFragment :one
insert into entity.fragment (
    id, workspace_id, kind, value, origin, first_seen, last_seen, observations, created_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict (workspace_id, kind, value) do update
set observations = entity.fragment.observations + excluded.observations,
    first_seen   = least(entity.fragment.first_seen, excluded.first_seen),
    last_seen    = greatest(entity.fragment.last_seen, excluded.last_seen),
    origin       = case when excluded.origin = 'observed' then 'observed'
                        else entity.fragment.origin end
returning id, workspace_id, kind, value, origin, first_seen, last_seen,
          observations, judgement_state, judgement_by, judgement_at,
          judgement_reason, created_at, read_at, read_by, (xmax = 0) as inserted
`

type UpsertFragmentParams struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	Kind         string
	Value        string
	Origin       string
	FirstSeen    pgtype.Timestamptz
	LastSeen     pgtype.Timestamptz
	Observations int32
	CreatedAt    pgtype.Timestamptz
}

type UpsertFragmentRow struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	Kind            string
	Value           string
	Origin          string
	FirstSeen       pgtype.Timestamptz
	LastSeen        pgtype.Timestamptz
	Observations    int32
	JudgementState  string
	JudgementBy     pgtype.UUID
	JudgementAt     pgtype.Timestamptz
	JudgementReason pgtype.Text
	CreatedAt       pgtype.Timestamptz
	ReadAt          pgtype.Timestamptz
	ReadBy          pgtype.UUID
	Inserted        bool
}

// THE DEDUP, as one statement — decisions/0036. A fragment IS the tuple, so the
// conflict target is the tuple.
//
// `last_seen` uses greatest() and `first_seen` least(), so a re-extraction of an
// old artifact moves neither in the wrong direction. `observations` ADDS,
// because two statements about one fragment are two statements.
//
// ORIGIN is promoted, never demoted: a manual fragment a tool later finds
// becomes observed, which is a stronger claim than either alone. `least()` over
// the text does that by luck of the alphabet, so it is spelled out instead.
func (q *Queries) UpsertFragment(ctx context.Context, arg UpsertFragmentParams) (UpsertFragmentRow, error) {
	row := q.db.QueryRow(ctx, upsertFragment,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Value,
		arg.Origin,
		arg.FirstSeen,
		arg.LastSeen,
		arg.Observations,
		arg.CreatedAt,
	)
	var i UpsertFragmentRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Value,
		&i.Origin,
		&i.FirstSeen,
		&i.LastSeen,
		&i.Observations,
		&i.JudgementState,
		&i.JudgementBy,
		&i.JudgementAt,
		&i.JudgementReason,
		&i.CreatedAt,
		&i.ReadAt,
		&i.ReadBy,
		&i.Inserted,
	)
	return i, err
}
