// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package entitydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EntityAsset struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	Kind            string
	Value           string
	Origin          string
	FirstSeen       pgtype.Timestamptz
	LastSeen        pgtype.Timestamptz
	Observations    int32
	JudgementState  string
	JudgementBy     pgtype.UUID
	JudgementAt     pgtype.Timestamptz
	JudgementReason pgtype.Text
	CreatedAt       pgtype.Timestamptz
	ReadAt          pgtype.Timestamptz
	ReadBy          pgtype.UUID
	AttributionID   pgtype.UUID
	Claimant        string
	Basis           string
	RootEntityID    pgtype.UUID
	TargetID        pgtype.UUID
}

type EntityAttribution struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	EntityID    pgtype.UUID
	FragmentID  pgtype.UUID
	Claimant    string
	ClaimantRef pgtype.UUID
	Confidence  pgtype.Float8
	Basis       string
	State       string
	DecidedAt   pgtype.Timestamptz
	DecidedBy   pgtype.UUID
	DecidedNote pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type EntityEntity struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	Kind            string
	Label           string
	TargetID        pgtype.UUID
	JudgementState  string
	JudgementBy     pgtype.UUID
	JudgementAt     pgtype.Timestamptz
	JudgementReason pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type EntityFragment struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	Kind            string
	Value           string
	Origin          string
	FirstSeen       pgtype.Timestamptz
	LastSeen        pgtype.Timestamptz
	Observations    int32
	JudgementState  string
	JudgementBy     pgtype.UUID
	JudgementAt     pgtype.Timestamptz
	JudgementReason pgtype.Text
	CreatedAt       pgtype.Timestamptz
	ReadAt          pgtype.Timestamptz
	ReadBy          pgtype.UUID
}
