// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package rundb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RunArtifact struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	InvocationID pgtype.UUID
	Stream       string
	Hash         string
	Bytes        int64
	Truncated    bool
	MediaType    pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type RunCandidate struct {
	ID            pgtype.UUID
	WorkspaceID   pgtype.UUID
	RunID         pgtype.UUID
	InvocationID  pgtype.UUID
	Kind          string
	Value         string
	Permitted     bool
	RefusalRule   pgtype.UUID
	RefusalReason pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type RunInvocation struct {
	ID             pgtype.UUID
	RunID          pgtype.UUID
	WorkspaceID    pgtype.UUID
	StepID         pgtype.UUID
	ToolID         pgtype.UUID
	Sequence       int32
	Phase          string
	Argv           []string
	BinaryPath     pgtype.Text
	ExitCode       pgtype.Int4
	Signal         pgtype.Text
	RefusalRule    pgtype.UUID
	RefusalReason  pgtype.Text
	SkippedBecause pgtype.Text
	Unavailable    pgtype.Text
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	DurationMs     int64
	PermitRule     pgtype.UUID
	Feeds          []pgtype.UUID
}

type RunRun struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	TargetID    pgtype.UUID
	CheckID     pgtype.UUID
	State       string
	StartedBy   pgtype.UUID
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	Version     int32
}
