// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run.sql

package rundb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const artifactByID = `-- name: ArtifactByID :one
select id, workspace_id, invocation_id, stream, hash, bytes, truncated,
       media_type, created_at
from run.artifact where id = $1 and workspace_id = $2
`

type ArtifactByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) ArtifactByID(ctx context.Context, arg ArtifactByIDParams) (RunArtifact, error) {
	row := q.db.QueryRow(ctx, artifactByID, arg.ID, arg.WorkspaceID)
	var i RunArtifact
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InvocationID,
		&i.Stream,
		&i.Hash,
		&i.Bytes,
		&i.Truncated,
		&i.MediaType,
		&i.CreatedAt,
	)
	return i, err
}

const artifactsForInvocation = `-- name: ArtifactsForInvocation :many
select id, workspace_id, invocation_id, stream, hash, bytes, truncated,
       media_type, created_at
from run.artifact where invocation_id = $1 order by stream
`

func (q *Queries) ArtifactsForInvocation(ctx context.Context, invocationID pgtype.UUID) ([]RunArtifact, error) {
	rows, err := q.db.Query(ctx, artifactsForInvocation, invocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunArtifact{}
	for rows.Next() {
		var i RunArtifact
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InvocationID,
			&i.Stream,
			&i.Hash,
			&i.Bytes,
			&i.Truncated,
			&i.MediaType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimRun = `-- name: ClaimRun :many
select r.id, r.workspace_id, r.target_id, r.check_id, r.state, r.started_by,
       r.started_at, r.finished_at, r.version
from run.run r
where r.state = 'running'
order by r.started_at
limit $1::int
for update of r skip locked
`

// The worker's read — decisions/0033. FOR UPDATE SKIP LOCKED so two workers
// never claim one run, and so a worker that dies mid-run leaves the row visible
// to the next boot rather than losing it.
//
// THE PREDICATE IS `state = 'running'` AND NOTHING ELSE. It once also required a
// PENDING invocation, which read as an optimisation and was a bug: a run whose
// every step the spawn gate refused has nothing pending, was never claimed, and
// sat at `running` forever — while being, by 0033, a COMPLETE answer to "may we
// look at this".
//
// Claiming a run with no work is cheap and it is what finishes it. There is
// deliberately no separate "unclaimed" flag: a state that can get out of step
// with the work is the thing that produced the bug above.
func (q *Queries) ClaimRun(ctx context.Context, batch int32) ([]RunRun, error) {
	rows, err := q.db.Query(ctx, claimRun, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunRun{}
	for rows.Next() {
		var i RunRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TargetID,
			&i.CheckID,
			&i.State,
			&i.StartedBy,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishRun = `-- name: FinishRun :execrows
update run.run
set state = $3, finished_at = $4, version = $5
where id = $1 and workspace_id = $2 and version = $6
`

type FinishRunParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	State       string
	FinishedAt  pgtype.Timestamptz
	Version     int32
	Version_2   int32
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishRun,
		arg.ID,
		arg.WorkspaceID,
		arg.State,
		arg.FinishedAt,
		arg.Version,
		arg.Version_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertArtifact = `-- name: InsertArtifact :exec
insert into run.artifact (
    id, workspace_id, invocation_id, stream, hash, bytes, truncated,
    media_type, created_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict (invocation_id, stream) do nothing
`

type InsertArtifactParams struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	InvocationID pgtype.UUID
	Stream       string
	Hash         string
	Bytes        int64
	Truncated    bool
	MediaType    pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

// A retried write of the same bytes is one blob and must be one row. The
// content address makes the second write identical, so ignoring it is correct
// rather than merely convenient.
func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) error {
	_, err := q.db.Exec(ctx, insertArtifact,
		arg.ID,
		arg.WorkspaceID,
		arg.InvocationID,
		arg.Stream,
		arg.Hash,
		arg.Bytes,
		arg.Truncated,
		arg.MediaType,
		arg.CreatedAt,
	)
	return err
}

const insertInvocation = `-- name: InsertInvocation :exec
insert into run.invocation (
    id, run_id, workspace_id, step_id, tool_id, sequence, phase,
    argv, binary_path, exit_code, signal, refusal_rule, refusal_reason,
    skipped_because, unavailable, started_at, finished_at, duration_ms, permit_rule,
    subject_kind, subject_value
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
`

type InsertInvocationParams struct {
	ID             pgtype.UUID
	RunID          pgtype.UUID
	WorkspaceID    pgtype.UUID
	StepID         pgtype.UUID
	ToolID         pgtype.UUID
	Sequence       int32
	Phase          string
	Argv           []string
	BinaryPath     pgtype.Text
	ExitCode       pgtype.Int4
	Signal         pgtype.Text
	RefusalRule    pgtype.UUID
	RefusalReason  pgtype.Text
	SkippedBecause pgtype.Text
	Unavailable    pgtype.Text
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	DurationMs     int64
	PermitRule     pgtype.UUID
	SubjectKind    pgtype.Text
	SubjectValue   pgtype.Text
}

func (q *Queries) InsertInvocation(ctx context.Context, arg InsertInvocationParams) error {
	_, err := q.db.Exec(ctx, insertInvocation,
		arg.ID,
		arg.RunID,
		arg.WorkspaceID,
		arg.StepID,
		arg.ToolID,
		arg.Sequence,
		arg.Phase,
		arg.Argv,
		arg.BinaryPath,
		arg.ExitCode,
		arg.Signal,
		arg.RefusalRule,
		arg.RefusalReason,
		arg.SkippedBecause,
		arg.Unavailable,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.PermitRule,
		arg.SubjectKind,
		arg.SubjectValue,
	)
	return err
}

const insertRun = `-- name: InsertRun :exec
insert into run.run (
    id, workspace_id, target_id, check_id, state, started_by,
    started_at, finished_at, version
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertRunParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	TargetID    pgtype.UUID
	CheckID     pgtype.UUID
	State       string
	StartedBy   pgtype.UUID
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	Version     int32
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) error {
	_, err := q.db.Exec(ctx, insertRun,
		arg.ID,
		arg.WorkspaceID,
		arg.TargetID,
		arg.CheckID,
		arg.State,
		arg.StartedBy,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Version,
	)
	return err
}

const invocationByID = `-- name: InvocationByID :one
select id, run_id, workspace_id, step_id, tool_id, sequence, phase,
       argv, binary_path, exit_code, signal, refusal_rule, refusal_reason,
       skipped_because, unavailable, started_at, finished_at, duration_ms, permit_rule,
       subject_kind, subject_value
from run.invocation where id = $1 and workspace_id = $2
`

type InvocationByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) InvocationByID(ctx context.Context, arg InvocationByIDParams) (RunInvocation, error) {
	row := q.db.QueryRow(ctx, invocationByID, arg.ID, arg.WorkspaceID)
	var i RunInvocation
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.WorkspaceID,
		&i.StepID,
		&i.ToolID,
		&i.Sequence,
		&i.Phase,
		&i.Argv,
		&i.BinaryPath,
		&i.ExitCode,
		&i.Signal,
		&i.RefusalRule,
		&i.RefusalReason,
		&i.SkippedBecause,
		&i.Unavailable,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.PermitRule,
		&i.SubjectKind,
		&i.SubjectValue,
	)
	return i, err
}

const invocationChecks = `-- name: InvocationChecks :many
select i.id as invocation_id, r.check_id
from run.invocation i
join run.run r on r.id = i.run_id
where i.workspace_id = $1
  and ($2::uuid is null or r.target_id = $2::uuid)
`

type InvocationChecksParams struct {
	WorkspaceID pgtype.UUID
	Target      pgtype.UUID
}

type InvocationChecksRow struct {
	InvocationID pgtype.UUID
	CheckID      pgtype.UUID
}

// Which CHECK each invocation belonged to — the other half of coverage's join,
// because a discovery tool is aimed at a seed and finds new subjects, and both
// are "this check looked at this asset".
func (q *Queries) InvocationChecks(ctx context.Context, arg InvocationChecksParams) ([]InvocationChecksRow, error) {
	rows, err := q.db.Query(ctx, invocationChecks, arg.WorkspaceID, arg.Target)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvocationChecksRow{}
	for rows.Next() {
		var i InvocationChecksRow
		if err := rows.Scan(&i.InvocationID, &i.CheckID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const invocationsForRun = `-- name: InvocationsForRun :many
select id, run_id, workspace_id, step_id, tool_id, sequence, phase,
       argv, binary_path, exit_code, signal, refusal_rule, refusal_reason,
       skipped_because, unavailable, started_at, finished_at, duration_ms, permit_rule,
       subject_kind, subject_value
from run.invocation where run_id = $1 order by sequence
`

func (q *Queries) InvocationsForRun(ctx context.Context, runID pgtype.UUID) ([]RunInvocation, error) {
	rows, err := q.db.Query(ctx, invocationsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunInvocation{}
	for rows.Next() {
		var i RunInvocation
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.WorkspaceID,
			&i.StepID,
			&i.ToolID,
			&i.Sequence,
			&i.Phase,
			&i.Argv,
			&i.BinaryPath,
			&i.ExitCode,
			&i.Signal,
			&i.RefusalRule,
			&i.RefusalReason,
			&i.SkippedBecause,
			&i.Unavailable,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.PermitRule,
			&i.SubjectKind,
			&i.SubjectValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastStartedPerPair = `-- name: LastStartedPerPair :many
select target_id, check_id, max(started_at)::timestamptz as last_started
from run.run
group by target_id, check_id
`

type LastStartedPerPairRow struct {
	TargetID    pgtype.UUID
	CheckID     pgtype.UUID
	LastStarted pgtype.Timestamptz
}

// The newest START of each (target, check) — decisions/0038 §5.
//
// Nothing new is stored: a `next_due` column would be a second authority over a
// time this table already knows, and it would be wrong every time an interval
// changed. `run_check` already indexes it.
//
// GLOBAL, with no workspace filter, because the scheduler is one lifecycle for
// the whole process — the same shape the executor's claim has.
func (q *Queries) LastStartedPerPair(ctx context.Context) ([]LastStartedPerPairRow, error) {
	rows, err := q.db.Query(ctx, lastStartedPerPair)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastStartedPerPairRow{}
	for rows.Next() {
		var i LastStartedPerPairRow
		if err := rows.Scan(&i.TargetID, &i.CheckID, &i.LastStarted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestCheckedPerSubject = `-- name: LatestCheckedPerSubject :many
select r.check_id, i.subject_kind, i.subject_value,
       max(i.finished_at)::timestamptz as last_checked
from run.invocation i
join run.run r on r.id = i.run_id
where i.workspace_id = $1
  and i.subject_value is not null
  and i.finished_at is not null
  and i.phase in ('ok', 'failed')
  and ($2::uuid is null or r.target_id = $2::uuid)
group by r.check_id, i.subject_kind, i.subject_value
`

type LatestCheckedPerSubjectParams struct {
	WorkspaceID pgtype.UUID
	Target      pgtype.UUID
}

type LatestCheckedPerSubjectRow struct {
	CheckID      pgtype.UUID
	SubjectKind  pgtype.Text
	SubjectValue pgtype.Text
	LastChecked  pgtype.Timestamptz
}

// What COVERAGE reads — decisions/0037. For one engagement, the newest FINISHED
// invocation per (check, subject).
//
// `finished_at is not null` and not `phase = 'ok'`: a check that RAN and found
// nothing has been checked, and a check that ran and BROKE has been attempted.
// Only `pending` and `refused` are excluded, and both are "no process existed".
//
// A REFUSED invocation is deliberately not a check. The scope gate said no, so
// nothing looked — which is `never`, and rendering it as checked would make a
// refusal look like coverage.
func (q *Queries) LatestCheckedPerSubject(ctx context.Context, arg LatestCheckedPerSubjectParams) ([]LatestCheckedPerSubjectRow, error) {
	rows, err := q.db.Query(ctx, latestCheckedPerSubject, arg.WorkspaceID, arg.Target)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestCheckedPerSubjectRow{}
	for rows.Next() {
		var i LatestCheckedPerSubjectRow
		if err := rows.Scan(
			&i.CheckID,
			&i.SubjectKind,
			&i.SubjectValue,
			&i.LastChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refusalsForRule = `-- name: RefusalsForRule :many
select id, run_id, workspace_id, step_id, tool_id, sequence, phase,
       argv, binary_path, exit_code, signal, refusal_rule, refusal_reason,
       skipped_because, unavailable, started_at, finished_at, duration_ms, permit_rule,
       subject_kind, subject_value
from run.invocation
where workspace_id = $1 and refusal_rule = $2
order by finished_at desc
limit $3::int
`

type RefusalsForRuleParams struct {
	WorkspaceID pgtype.UUID
	RefusalRule pgtype.UUID
	Page        int32
}

// What makes an append-only scope ledger worth keeping: which spawns did this
// rule refuse. 0030 keeps the rule because three surfaces cite it; this is one.
func (q *Queries) RefusalsForRule(ctx context.Context, arg RefusalsForRuleParams) ([]RunInvocation, error) {
	rows, err := q.db.Query(ctx, refusalsForRule, arg.WorkspaceID, arg.RefusalRule, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunInvocation{}
	for rows.Next() {
		var i RunInvocation
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.WorkspaceID,
			&i.StepID,
			&i.ToolID,
			&i.Sequence,
			&i.Phase,
			&i.Argv,
			&i.BinaryPath,
			&i.ExitCode,
			&i.Signal,
			&i.RefusalRule,
			&i.RefusalReason,
			&i.SkippedBecause,
			&i.Unavailable,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.PermitRule,
			&i.SubjectKind,
			&i.SubjectValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runByID = `-- name: RunByID :one
select id, workspace_id, target_id, check_id, state, started_by,
       started_at, finished_at, version
from run.run where id = $1 and workspace_id = $2
`

type RunByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

// BOTH IDS. A run read without its engagement is another client's.
func (q *Queries) RunByID(ctx context.Context, arg RunByIDParams) (RunRun, error) {
	row := q.db.QueryRow(ctx, runByID, arg.ID, arg.WorkspaceID)
	var i RunRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TargetID,
		&i.CheckID,
		&i.State,
		&i.StartedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Version,
	)
	return i, err
}

const runsForWorkspace = `-- name: RunsForWorkspace :many
select id, workspace_id, target_id, check_id, state, started_by,
       started_at, finished_at, version
from run.run
where workspace_id = $1
  and ($2::uuid is null or target_id = $2::uuid)
  and ($3::timestamptz is null
       or (started_at, id) < ($3::timestamptz, $4::uuid))
order by started_at desc, id desc
limit $5::int
`

type RunsForWorkspaceParams struct {
	WorkspaceID pgtype.UUID
	Target      pgtype.UUID
	Before      pgtype.Timestamptz
	BeforeID    pgtype.UUID
	Page        int32
}

// Newest first, and PAGED BY A CURSOR rather than an offset — the same keyset
// shape the audit ledger uses, because this list only grows.
func (q *Queries) RunsForWorkspace(ctx context.Context, arg RunsForWorkspaceParams) ([]RunRun, error) {
	rows, err := q.db.Query(ctx, runsForWorkspace,
		arg.WorkspaceID,
		arg.Target,
		arg.Before,
		arg.BeforeID,
		arg.Page,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunRun{}
	for rows.Next() {
		var i RunRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TargetID,
			&i.CheckID,
			&i.State,
			&i.StartedBy,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveInvocation = `-- name: SaveInvocation :execrows
update run.invocation
set phase = $2, argv = $3, binary_path = $4, exit_code = $5, signal = $6,
    refusal_rule = $7, refusal_reason = $8, skipped_because = $9,
    unavailable = $10, started_at = $11, finished_at = $12, duration_ms = $13,
    permit_rule = $14
where id = $1
`

type SaveInvocationParams struct {
	ID             pgtype.UUID
	Phase          string
	Argv           []string
	BinaryPath     pgtype.Text
	ExitCode       pgtype.Int4
	Signal         pgtype.Text
	RefusalRule    pgtype.UUID
	RefusalReason  pgtype.Text
	SkippedBecause pgtype.Text
	Unavailable    pgtype.Text
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	DurationMs     int64
	PermitRule     pgtype.UUID
}

// Every column an outcome can touch. It must match what the domain can change —
// an UPDATE that silently omits one returns a correctly-moved record having
// moved nothing, which identity's ConfirmEmailChange did for a day.
func (q *Queries) SaveInvocation(ctx context.Context, arg SaveInvocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveInvocation,
		arg.ID,
		arg.Phase,
		arg.Argv,
		arg.BinaryPath,
		arg.ExitCode,
		arg.Signal,
		arg.RefusalRule,
		arg.RefusalReason,
		arg.SkippedBecause,
		arg.Unavailable,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.PermitRule,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
