// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package workspacedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WorkspaceWorkspace struct {
	ID            pgtype.UUID
	OrgID         pgtype.UUID
	Name          string
	Status        string
	Version       int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ArchivedAt    pgtype.Timestamptz
	SourceEventID pgtype.UUID
	CreatedBy     pgtype.UUID
}
