// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package workspacedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertWorkspace = `-- name: InsertWorkspace :exec
insert into workspace.workspace (
    id, org_id, name, status, version, created_at, updated_at, archived_at, source_event_id
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertWorkspaceParams struct {
	ID            pgtype.UUID
	OrgID         pgtype.UUID
	Name          string
	Status        string
	Version       int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ArchivedAt    pgtype.Timestamptz
	SourceEventID pgtype.UUID
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) error {
	_, err := q.db.Exec(ctx, insertWorkspace,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ArchivedAt,
		arg.SourceEventID,
	)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :execrows
update workspace.workspace
set name = $2, status = $3, version = $4, updated_at = $5, archived_at = $6
where id = $1 and version = $7
`

type UpdateWorkspaceParams struct {
	ID         pgtype.UUID
	Name       string
	Status     string
	Version    int32
	UpdatedAt  pgtype.Timestamptz
	ArchivedAt pgtype.Timestamptz
	Version_2  int32
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.Version,
		arg.UpdatedAt,
		arg.ArchivedAt,
		arg.Version_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const workspaceByID = `-- name: WorkspaceByID :one
select id, org_id, name, status, version, created_at, updated_at, archived_at, source_event_id
from workspace.workspace where id = $1
`

func (q *Queries) WorkspaceByID(ctx context.Context, id pgtype.UUID) (WorkspaceWorkspace, error) {
	row := q.db.QueryRow(ctx, workspaceByID, id)
	var i WorkspaceWorkspace
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.SourceEventID,
	)
	return i, err
}

const workspaceBySourceEvent = `-- name: WorkspaceBySourceEvent :one
select id, org_id, name, status, version, created_at, updated_at, archived_at, source_event_id
from workspace.workspace where source_event_id = $1
`

func (q *Queries) WorkspaceBySourceEvent(ctx context.Context, sourceEventID pgtype.UUID) (WorkspaceWorkspace, error) {
	row := q.db.QueryRow(ctx, workspaceBySourceEvent, sourceEventID)
	var i WorkspaceWorkspace
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.SourceEventID,
	)
	return i, err
}

const workspacesForOrg = `-- name: WorkspacesForOrg :many
select id, org_id, name, status, version, created_at, updated_at, archived_at, source_event_id
from workspace.workspace
where org_id = $1 and status <> 'archived'
order by created_at
`

func (q *Queries) WorkspacesForOrg(ctx context.Context, orgID pgtype.UUID) ([]WorkspaceWorkspace, error) {
	rows, err := q.db.Query(ctx, workspacesForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceWorkspace{}
	for rows.Next() {
		var i WorkspaceWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.SourceEventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
