// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: check.sql

package checkdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkByID = `-- name: CheckByID :one
select id, org_id, name, question, applies_to, interval_seconds, enabled,
       status, version, created_by, created_at, updated_at, archived_at, human
from checks.check where id = $1 and org_id = $2
`

type CheckByIDParams struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
}

// BOTH IDS. A check read without its org is another firm's.
func (q *Queries) CheckByID(ctx context.Context, arg CheckByIDParams) (ChecksCheck, error) {
	row := q.db.QueryRow(ctx, checkByID, arg.ID, arg.OrgID)
	var i ChecksCheck
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Question,
		&i.AppliesTo,
		&i.IntervalSeconds,
		&i.Enabled,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Human,
	)
	return i, err
}

const checksForOrg = `-- name: ChecksForOrg :many
select id, org_id, name, question, applies_to, interval_seconds, enabled,
       status, version, created_by, created_at, updated_at, archived_at, human
from checks.check
where org_id = $1 and ($2::bool or status <> 'archived')
order by lower(name)
`

type ChecksForOrgParams struct {
	OrgID           pgtype.UUID
	IncludeArchived bool
}

func (q *Queries) ChecksForOrg(ctx context.Context, arg ChecksForOrgParams) ([]ChecksCheck, error) {
	rows, err := q.db.Query(ctx, checksForOrg, arg.OrgID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecksCheck{}
	for rows.Next() {
		var i ChecksCheck
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Question,
			&i.AppliesTo,
			&i.IntervalSeconds,
			&i.Enabled,
			&i.Status,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Human,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checksUsingTool = `-- name: ChecksUsingTool :many
select distinct c.id, c.name
from checks.check c
join checks.step s on s.check_id = c.id
where c.org_id = $1 and s.tool_id = $2 and c.status <> 'archived'
order by c.name
`

type ChecksUsingToolParams struct {
	OrgID  pgtype.UUID
	ToolID pgtype.UUID
}

type ChecksUsingToolRow struct {
	ID   pgtype.UUID
	Name string
}

// What archiving a tool has to ask, and the reason the chain is rows rather than
// a jsonb column — 0032. A blob answers this with a scan and a parse.
func (q *Queries) ChecksUsingTool(ctx context.Context, arg ChecksUsingToolParams) ([]ChecksUsingToolRow, error) {
	rows, err := q.db.Query(ctx, checksUsingTool, arg.OrgID, arg.ToolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecksUsingToolRow{}
	for rows.Next() {
		var i ChecksUsingToolRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFlowsForCheck = `-- name: DeleteFlowsForCheck :exec
delete from checks.flow where check_id = $1
`

// Flows ARE replaced wholesale, unlike steps. Nothing cites an edge — an
// invocation names a step — so there is no identity to preserve, and a diff
// would be more code for a set of two-column rows.
func (q *Queries) DeleteFlowsForCheck(ctx context.Context, checkID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlowsForCheck, checkID)
	return err
}

const deleteStepsExcept = `-- name: DeleteStepsExcept :exec
delete from checks.step where check_id = $1 and not (id = any($2::uuid[]))
`

type DeleteStepsExceptParams struct {
	CheckID pgtype.UUID
	Keep    []pgtype.UUID
}

// Removing a step removes its flows too, and this runs BEFORE the flow rewrite
// so an orphan edge never exists even inside the transaction.
func (q *Queries) DeleteStepsExcept(ctx context.Context, arg DeleteStepsExceptParams) error {
	_, err := q.db.Exec(ctx, deleteStepsExcept, arg.CheckID, arg.Keep)
	return err
}

const flowsForCheck = `-- name: FlowsForCheck :many
select check_id, from_step, to_step
from checks.flow where check_id = $1 order by from_step, to_step
`

func (q *Queries) FlowsForCheck(ctx context.Context, checkID pgtype.UUID) ([]ChecksFlow, error) {
	rows, err := q.db.Query(ctx, flowsForCheck, checkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecksFlow{}
	for rows.Next() {
		var i ChecksFlow
		if err := rows.Scan(&i.CheckID, &i.FromStep, &i.ToStep); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCheck = `-- name: InsertCheck :exec
insert into checks.check (
    id, org_id, name, question, applies_to, interval_seconds, enabled,
    status, version, created_by, created_at, updated_at, archived_at, human
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertCheckParams struct {
	ID              pgtype.UUID
	OrgID           pgtype.UUID
	Name            string
	Question        string
	AppliesTo       []string
	IntervalSeconds pgtype.Int4
	Enabled         bool
	Status          string
	Version         int32
	CreatedBy       pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ArchivedAt      pgtype.Timestamptz
	Human           bool
}

func (q *Queries) InsertCheck(ctx context.Context, arg InsertCheckParams) error {
	_, err := q.db.Exec(ctx, insertCheck,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Question,
		arg.AppliesTo,
		arg.IntervalSeconds,
		arg.Enabled,
		arg.Status,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ArchivedAt,
		arg.Human,
	)
	return err
}

const insertFlow = `-- name: InsertFlow :exec
insert into checks.flow (check_id, from_step, to_step) values ($1, $2, $3)
`

type InsertFlowParams struct {
	CheckID  pgtype.UUID
	FromStep pgtype.UUID
	ToStep   pgtype.UUID
}

func (q *Queries) InsertFlow(ctx context.Context, arg InsertFlowParams) error {
	_, err := q.db.Exec(ctx, insertFlow, arg.CheckID, arg.FromStep, arg.ToStep)
	return err
}

const insertStep = `-- name: InsertStep :exec
insert into checks.step (id, check_id, tool_id, x, y, pinned)
values ($1, $2, $3, $4, $5, $6)
`

type InsertStepParams struct {
	ID      pgtype.UUID
	CheckID pgtype.UUID
	ToolID  pgtype.UUID
	X       int32
	Y       int32
	Pinned  bool
}

func (q *Queries) InsertStep(ctx context.Context, arg InsertStepParams) error {
	_, err := q.db.Exec(ctx, insertStep,
		arg.ID,
		arg.CheckID,
		arg.ToolID,
		arg.X,
		arg.Y,
		arg.Pinned,
	)
	return err
}

const schedulableChecks = `-- name: SchedulableChecks :many
select id, org_id, name, question, applies_to, interval_seconds, enabled,
       status, version, created_by, created_at, updated_at, archived_at, human
from checks.check
where status <> 'archived'
  and enabled
  and not human
  and interval_seconds is not null
order by org_id, lower(name)
`

// Every check that a schedule could start, ACROSS ALL ORGS — decisions/0038 §4.
//
// The scheduler is driven from here because checks are the smallest set: a firm
// has six, not six thousand targets. The three exclusions are three different
// facts, and none of them is "this check is broken":
//
//	not enabled     the standing authorisation is withdrawn
//	human           nothing spawns; a person reading it is the whole act
//	no interval     it runs when somebody asks, not on a clock
func (q *Queries) SchedulableChecks(ctx context.Context) ([]ChecksCheck, error) {
	rows, err := q.db.Query(ctx, schedulableChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecksCheck{}
	for rows.Next() {
		var i ChecksCheck
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Question,
			&i.AppliesTo,
			&i.IntervalSeconds,
			&i.Enabled,
			&i.Status,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Human,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stepsForCheck = `-- name: StepsForCheck :many
select id, check_id, tool_id, x, y, pinned
from checks.step where check_id = $1 order by id
`

func (q *Queries) StepsForCheck(ctx context.Context, checkID pgtype.UUID) ([]ChecksStep, error) {
	rows, err := q.db.Query(ctx, stepsForCheck, checkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecksStep{}
	for rows.Next() {
		var i ChecksStep
		if err := rows.Scan(
			&i.ID,
			&i.CheckID,
			&i.ToolID,
			&i.X,
			&i.Y,
			&i.Pinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheck = `-- name: UpdateCheck :execrows
update checks.check
set name = $3, question = $4, applies_to = $5, interval_seconds = $6,
    enabled = $7, status = $8, version = $9, updated_at = $10, archived_at = $11,
    human = $12
where id = $1 and org_id = $2 and version = $13
`

type UpdateCheckParams struct {
	ID              pgtype.UUID
	OrgID           pgtype.UUID
	Name            string
	Question        string
	AppliesTo       []string
	IntervalSeconds pgtype.Int4
	Enabled         bool
	Status          string
	Version         int32
	UpdatedAt       pgtype.Timestamptz
	ArchivedAt      pgtype.Timestamptz
	Human           bool
	Version_2       int32
}

// The column list must match what the domain can change.
func (q *Queries) UpdateCheck(ctx context.Context, arg UpdateCheckParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCheck,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Question,
		arg.AppliesTo,
		arg.IntervalSeconds,
		arg.Enabled,
		arg.Status,
		arg.Version,
		arg.UpdatedAt,
		arg.ArchivedAt,
		arg.Human,
		arg.Version_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStep = `-- name: UpdateStep :execrows
update checks.step set tool_id = $3, x = $4, y = $5, pinned = $6
where id = $1 and check_id = $2
`

type UpdateStepParams struct {
	ID      pgtype.UUID
	CheckID pgtype.UUID
	ToolID  pgtype.UUID
	X       int32
	Y       int32
	Pinned  bool
}

// A step's TOOL can change and its ID cannot — that is the whole reason a save
// is a diff rather than a delete-and-insert.
func (q *Queries) UpdateStep(ctx context.Context, arg UpdateStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStep,
		arg.ID,
		arg.CheckID,
		arg.ToolID,
		arg.X,
		arg.Y,
		arg.Pinned,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
