// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package checkdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChecksCheck struct {
	ID              pgtype.UUID
	OrgID           pgtype.UUID
	Name            string
	Question        string
	AppliesTo       []string
	IntervalSeconds pgtype.Int4
	Enabled         bool
	Status          string
	Version         int32
	CreatedBy       pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ArchivedAt      pgtype.Timestamptz
	Human           bool
}

type ChecksFlow struct {
	CheckID  pgtype.UUID
	FromStep pgtype.UUID
	ToStep   pgtype.UUID
}

type ChecksStep struct {
	ID      pgtype.UUID
	CheckID pgtype.UUID
	ToolID  pgtype.UUID
	X       int32
	Y       int32
	Pinned  bool
}
