// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reportdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ReportReport struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	TargetID    pgtype.UUID
	Title       string
	PreparedBy  pgtype.Text
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
	Revisions   int32
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ReportRevision struct {
	ID          pgtype.UUID
	ReportID    pgtype.UUID
	WorkspaceID pgtype.UUID
	Number      int32
	Hash        string
	Bytes       int64
	MediaType   string
	Sections    []string
	IssuedBy    pgtype.UUID
	IssuedAt    pgtype.Timestamptz
}

type ReportSection struct {
	ReportID pgtype.UUID
	Section  string
	Enabled  bool
}
