// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package reportdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertReport = `-- name: InsertReport :exec
insert into report.report (
    id, workspace_id, target_id, title, prepared_by,
    period_start, period_end, revisions, created_by, created_at, updated_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertReportParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	TargetID    pgtype.UUID
	Title       string
	PreparedBy  pgtype.Text
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
	Revisions   int32
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) error {
	_, err := q.db.Exec(ctx, insertReport,
		arg.ID,
		arg.WorkspaceID,
		arg.TargetID,
		arg.Title,
		arg.PreparedBy,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Revisions,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertRevision = `-- name: InsertRevision :exec
insert into report.revision (
    id, report_id, workspace_id, number, hash, bytes, media_type,
    sections, issued_by, issued_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertRevisionParams struct {
	ID          pgtype.UUID
	ReportID    pgtype.UUID
	WorkspaceID pgtype.UUID
	Number      int32
	Hash        string
	Bytes       int64
	MediaType   string
	Sections    []string
	IssuedBy    pgtype.UUID
	IssuedAt    pgtype.Timestamptz
}

func (q *Queries) InsertRevision(ctx context.Context, arg InsertRevisionParams) error {
	_, err := q.db.Exec(ctx, insertRevision,
		arg.ID,
		arg.ReportID,
		arg.WorkspaceID,
		arg.Number,
		arg.Hash,
		arg.Bytes,
		arg.MediaType,
		arg.Sections,
		arg.IssuedBy,
		arg.IssuedAt,
	)
	return err
}

const nextRevisionNumber = `-- name: NextRevisionNumber :one
select coalesce(max(number), 0)::int + 1 from report.revision where report_id = $1
`

// coalesce, because the first revision of a report has no predecessor and max()
// over no rows is null rather than zero.
func (q *Queries) NextRevisionNumber(ctx context.Context, reportID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextRevisionNumber, reportID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const reportByID = `-- name: ReportByID :one
select id, workspace_id, target_id, title, prepared_by, period_start, period_end,
       revisions, created_by, created_at, updated_at
from report.report where id = $1 and workspace_id = $2
`

type ReportByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

// BOTH IDS. A report read without its engagement is another client's.
func (q *Queries) ReportByID(ctx context.Context, arg ReportByIDParams) (ReportReport, error) {
	row := q.db.QueryRow(ctx, reportByID, arg.ID, arg.WorkspaceID)
	var i ReportReport
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TargetID,
		&i.Title,
		&i.PreparedBy,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Revisions,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reportsForTarget = `-- name: ReportsForTarget :many
select id, workspace_id, target_id, title, prepared_by, period_start, period_end,
       revisions, created_by, created_at, updated_at
from report.report
where workspace_id = $1
  and ($2::uuid is null or target_id = $2::uuid)
order by created_at desc
limit $3::int
`

type ReportsForTargetParams struct {
	WorkspaceID pgtype.UUID
	Target      pgtype.UUID
	Page        int32
}

func (q *Queries) ReportsForTarget(ctx context.Context, arg ReportsForTargetParams) ([]ReportReport, error) {
	rows, err := q.db.Query(ctx, reportsForTarget, arg.WorkspaceID, arg.Target, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportReport{}
	for rows.Next() {
		var i ReportReport
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TargetID,
			&i.Title,
			&i.PreparedBy,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Revisions,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revisionByID = `-- name: RevisionByID :one
select id, report_id, workspace_id, number, hash, bytes, media_type,
       sections, issued_by, issued_at
from report.revision where id = $1 and workspace_id = $2
`

type RevisionByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

// Read by WORKSPACE and not through its report, because a client reaching a
// delivered document must not need to read the configuration that produced it.
func (q *Queries) RevisionByID(ctx context.Context, arg RevisionByIDParams) (ReportRevision, error) {
	row := q.db.QueryRow(ctx, revisionByID, arg.ID, arg.WorkspaceID)
	var i ReportRevision
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.WorkspaceID,
		&i.Number,
		&i.Hash,
		&i.Bytes,
		&i.MediaType,
		&i.Sections,
		&i.IssuedBy,
		&i.IssuedAt,
	)
	return i, err
}

const revisionsForReport = `-- name: RevisionsForReport :many
select id, report_id, workspace_id, number, hash, bytes, media_type,
       sections, issued_by, issued_at
from report.revision where report_id = $1 order by number desc
`

func (q *Queries) RevisionsForReport(ctx context.Context, reportID pgtype.UUID) ([]ReportRevision, error) {
	rows, err := q.db.Query(ctx, revisionsForReport, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportRevision{}
	for rows.Next() {
		var i ReportRevision
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.WorkspaceID,
			&i.Number,
			&i.Hash,
			&i.Bytes,
			&i.MediaType,
			&i.Sections,
			&i.IssuedBy,
			&i.IssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveReport = `-- name: SaveReport :execrows
update report.report
set title = $3, prepared_by = $4, period_start = $5, period_end = $6,
    revisions = $7, updated_at = $8
where id = $1 and workspace_id = $2
`

type SaveReportParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Title       string
	PreparedBy  pgtype.Text
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
	Revisions   int32
	UpdatedAt   pgtype.Timestamptz
}

// Everything a person can edit. `revisions` moves here too, because issuing
// increments it in the same transaction that writes the revision — a count that
// could drift from the rows it counts is a count nobody can trust.
func (q *Queries) SaveReport(ctx context.Context, arg SaveReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveReport,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.PreparedBy,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Revisions,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sectionsForReport = `-- name: SectionsForReport :many
select section, enabled from report.section where report_id = $1
`

type SectionsForReportRow struct {
	Section string
	Enabled bool
}

func (q *Queries) SectionsForReport(ctx context.Context, reportID pgtype.UUID) ([]SectionsForReportRow, error) {
	rows, err := q.db.Query(ctx, sectionsForReport, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SectionsForReportRow{}
	for rows.Next() {
		var i SectionsForReportRow
		if err := rows.Scan(&i.Section, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSection = `-- name: SetSection :exec
insert into report.section (report_id, section, enabled)
values ($1, $2, $3)
on conflict (report_id, section) do update set enabled = excluded.enabled
`

type SetSectionParams struct {
	ReportID pgtype.UUID
	Section  string
	Enabled  bool
}

func (q *Queries) SetSection(ctx context.Context, arg SetSectionParams) error {
	_, err := q.db.Exec(ctx, setSection, arg.ReportID, arg.Section, arg.Enabled)
	return err
}
