// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package orgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrgMember struct {
	ID         pgtype.UUID
	OrgID      pgtype.UUID
	AccountID  pgtype.UUID
	Role       string
	Status     string
	Version    int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ArchivedAt pgtype.Timestamptz
}

type OrgOrg struct {
	ID            pgtype.UUID
	Name          string
	Version       int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	SourceEventID pgtype.UUID
}
