// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org.sql

package orgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLiveOwners = `-- name: CountLiveOwners :one
select count(*) from org.member
where org_id = $1 and role = 'owner' and status <> 'archived'
`

func (q *Queries) CountLiveOwners(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveOwners, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertMember = `-- name: InsertMember :exec
insert into org.member (
    id, org_id, account_id, role, status, version, created_at, updated_at, archived_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertMemberParams struct {
	ID         pgtype.UUID
	OrgID      pgtype.UUID
	AccountID  pgtype.UUID
	Role       string
	Status     string
	Version    int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ArchivedAt pgtype.Timestamptz
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.Exec(ctx, insertMember,
		arg.ID,
		arg.OrgID,
		arg.AccountID,
		arg.Role,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ArchivedAt,
	)
	return err
}

const insertOrg = `-- name: InsertOrg :exec
insert into org.org (id, name, version, created_at, updated_at)
values ($1, $2, $3, $4, $5)
`

type InsertOrgParams struct {
	ID        pgtype.UUID
	Name      string
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertOrg(ctx context.Context, arg InsertOrgParams) error {
	_, err := q.db.Exec(ctx, insertOrg,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const liveMemberFor = `-- name: LiveMemberFor :one
select id, org_id, account_id, role, status, version, created_at, updated_at, archived_at
from org.member
where org_id = $1 and account_id = $2 and status <> 'archived'
`

type LiveMemberForParams struct {
	OrgID     pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) LiveMemberFor(ctx context.Context, arg LiveMemberForParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, liveMemberFor, arg.OrgID, arg.AccountID)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AccountID,
		&i.Role,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const memberByID = `-- name: MemberByID :one
select id, org_id, account_id, role, status, version, created_at, updated_at, archived_at
from org.member where id = $1
`

func (q *Queries) MemberByID(ctx context.Context, id pgtype.UUID) (OrgMember, error) {
	row := q.db.QueryRow(ctx, memberByID, id)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AccountID,
		&i.Role,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const membersOf = `-- name: MembersOf :many
select id, org_id, account_id, role, status, version, created_at, updated_at, archived_at
from org.member
where org_id = $1
order by created_at
`

func (q *Queries) MembersOf(ctx context.Context, orgID pgtype.UUID) ([]OrgMember, error) {
	rows, err := q.db.Query(ctx, membersOf, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgMember{}
	for rows.Next() {
		var i OrgMember
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AccountID,
			&i.Role,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgByID = `-- name: OrgByID :one
select id, name, version, created_at, updated_at from org.org where id = $1
`

func (q *Queries) OrgByID(ctx context.Context, id pgtype.UUID) (OrgOrg, error) {
	row := q.db.QueryRow(ctx, orgByID, id)
	var i OrgOrg
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const orgsForAccount = `-- name: OrgsForAccount :many
select o.id, o.name, o.version, o.created_at, o.updated_at
from org.org o
join org.member m on m.org_id = o.id
where m.account_id = $1 and m.status <> 'archived'
order by o.created_at
`

func (q *Queries) OrgsForAccount(ctx context.Context, accountID pgtype.UUID) ([]OrgOrg, error) {
	rows, err := q.db.Query(ctx, orgsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgOrg{}
	for rows.Next() {
		var i OrgOrg
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :execrows
update org.member
set role = $2, status = $3, version = $4, updated_at = $5, archived_at = $6
where id = $1 and version = $7
`

type UpdateMemberParams struct {
	ID         pgtype.UUID
	Role       string
	Status     string
	Version    int32
	UpdatedAt  pgtype.Timestamptz
	ArchivedAt pgtype.Timestamptz
	Version_2  int32
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMember,
		arg.ID,
		arg.Role,
		arg.Status,
		arg.Version,
		arg.UpdatedAt,
		arg.ArchivedAt,
		arg.Version_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrg = `-- name: UpdateOrg :execrows
update org.org set name = $2, version = $3, updated_at = $4
where id = $1 and version = $5
`

type UpdateOrgParams struct {
	ID        pgtype.UUID
	Name      string
	Version   int32
	UpdatedAt pgtype.Timestamptz
	Version_2 int32
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrg,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.UpdatedAt,
		arg.Version_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
