// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: line.sql

package journaldb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const expireLinesBefore = `-- name: ExpireLinesBefore :execrows
delete from journal.line l
where l.id in (
    select c.id from journal.line c
    where c.occurred_at < $1 and c.decision = false
    limit $2
)
`

type ExpireLinesBeforeParams struct {
	OccurredAt pgtype.Timestamptz
	Limit      int32
}

// BATCHED, and the batch is a bound on the transaction rather than a throughput
// knob — decisions/0022. An unbounded delete against a year of accumulated rows
// is one transaction holding one very large lock.
//
// `decision = false` is the other half of the record: a decision is kept, so a
// chain older than the window degrades to its skeleton instead of disappearing.
func (q *Queries) ExpireLinesBefore(ctx context.Context, arg ExpireLinesBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireLinesBefore, arg.OccurredAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertLine = `-- name: InsertLine :execrows
insert into journal.line (
    id, event_id, action, subject, origin, actor, on_behalf_of, workspace_id,
    depth, attempt, decision, correlation_id, causation_id, detail,
    occurred_at, recorded_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
on conflict (event_id) do nothing
`

type InsertLineParams struct {
	ID            pgtype.UUID
	EventID       pgtype.UUID
	Action        string
	Subject       string
	Origin        string
	Actor         string
	OnBehalfOf    string
	WorkspaceID   string
	Depth         int32
	Attempt       int32
	Decision      bool
	CorrelationID pgtype.UUID
	CausationID   pgtype.UUID
	Detail        []byte
	OccurredAt    pgtype.Timestamptz
	RecordedAt    pgtype.Timestamptz
}

func (q *Queries) InsertLine(ctx context.Context, arg InsertLineParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLine,
		arg.ID,
		arg.EventID,
		arg.Action,
		arg.Subject,
		arg.Origin,
		arg.Actor,
		arg.OnBehalfOf,
		arg.WorkspaceID,
		arg.Depth,
		arg.Attempt,
		arg.Decision,
		arg.CorrelationID,
		arg.CausationID,
		arg.Detail,
		arg.OccurredAt,
		arg.RecordedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lineByID = `-- name: LineByID :one
select id, event_id, action, subject, origin, actor, on_behalf_of, workspace_id,
       depth, attempt, decision, correlation_id, causation_id, detail,
       occurred_at, recorded_at
from journal.line
where id = $1
`

func (q *Queries) LineByID(ctx context.Context, id pgtype.UUID) (JournalLine, error) {
	row := q.db.QueryRow(ctx, lineByID, id)
	var i JournalLine
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Action,
		&i.Subject,
		&i.Origin,
		&i.Actor,
		&i.OnBehalfOf,
		&i.WorkspaceID,
		&i.Depth,
		&i.Attempt,
		&i.Decision,
		&i.CorrelationID,
		&i.CausationID,
		&i.Detail,
		&i.OccurredAt,
		&i.RecordedAt,
	)
	return i, err
}

const linesForCorrelation = `-- name: LinesForCorrelation :many
select id, event_id, action, subject, origin, actor, on_behalf_of, workspace_id,
       depth, attempt, decision, correlation_id, causation_id, detail,
       occurred_at, recorded_at
from journal.line
where correlation_id = $1
order by occurred_at
`

func (q *Queries) LinesForCorrelation(ctx context.Context, correlationID pgtype.UUID) ([]JournalLine, error) {
	rows, err := q.db.Query(ctx, linesForCorrelation, correlationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalLine{}
	for rows.Next() {
		var i JournalLine
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Action,
			&i.Subject,
			&i.Origin,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.Depth,
			&i.Attempt,
			&i.Decision,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linesForOrigin = `-- name: LinesForOrigin :many
select id, event_id, action, subject, origin, actor, on_behalf_of, workspace_id,
       depth, attempt, decision, correlation_id, causation_id, detail,
       occurred_at, recorded_at
from journal.line
where origin = $1
order by occurred_at desc
limit $2
`

type LinesForOriginParams struct {
	Origin string
	Limit  int32
}

func (q *Queries) LinesForOrigin(ctx context.Context, arg LinesForOriginParams) ([]JournalLine, error) {
	rows, err := q.db.Query(ctx, linesForOrigin, arg.Origin, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalLine{}
	for rows.Next() {
		var i JournalLine
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Action,
			&i.Subject,
			&i.Origin,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.Depth,
			&i.Attempt,
			&i.Decision,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentLines = `-- name: RecentLines :many
select id, event_id, action, subject, origin, actor, on_behalf_of, workspace_id,
       depth, attempt, decision, correlation_id, causation_id, detail,
       occurred_at, recorded_at
from journal.line
order by occurred_at desc
limit $1
`

func (q *Queries) RecentLines(ctx context.Context, limit int32) ([]JournalLine, error) {
	rows, err := q.db.Query(ctx, recentLines, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalLine{}
	for rows.Next() {
		var i JournalLine
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Action,
			&i.Subject,
			&i.Origin,
			&i.Actor,
			&i.OnBehalfOf,
			&i.WorkspaceID,
			&i.Depth,
			&i.Attempt,
			&i.Decision,
			&i.CorrelationID,
			&i.CausationID,
			&i.Detail,
			&i.OccurredAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
