// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package journaldb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type JournalLine struct {
	ID            pgtype.UUID
	EventID       pgtype.UUID
	Action        string
	Subject       string
	Origin        string
	Actor         string
	OnBehalfOf    string
	WorkspaceID   string
	Depth         int32
	Attempt       int32
	Decision      bool
	CorrelationID pgtype.UUID
	CausationID   pgtype.UUID
	Detail        []byte
	OccurredAt    pgtype.Timestamptz
	RecordedAt    pgtype.Timestamptz
}
