// Code generated by sqlc. DO NOT EDIT.
package seendb

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
)

const markerByAccountWorkspace = `-- name: MarkerByAccountWorkspace :one
select account_id, workspace_id, seen_at
from seen.marker
where account_id = $1 and workspace_id = $2
`

type MarkerByAccountWorkspaceParams struct {
	AccountID   pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) MarkerByAccountWorkspace(ctx context.Context, arg MarkerByAccountWorkspaceParams) (SeenMarker, error) {
	row := q.db.QueryRow(ctx, markerByAccountWorkspace, arg.AccountID, arg.WorkspaceID)
	var out SeenMarker
	err := row.Scan(&out.AccountID, &out.WorkspaceID, &out.SeenAt)
	return out, err
}

const upsertMarker = `-- name: UpsertMarker :exec
insert into seen.marker (account_id, workspace_id, seen_at)
values ($1, $2, $3)
on conflict (account_id, workspace_id) do update
set seen_at = excluded.seen_at
`

type UpsertMarkerParams struct {
	AccountID   pgtype.UUID
	WorkspaceID pgtype.UUID
	SeenAt      pgtype.Timestamptz
}

func (q *Queries) UpsertMarker(ctx context.Context, arg UpsertMarkerParams) error {
	_, err := q.db.Exec(ctx, upsertMarker, arg.AccountID, arg.WorkspaceID, arg.SeenAt)
	return err
}
