// Code generated by sqlc. DO NOT EDIT.
package seendb

import "github.com/jackc/pgx/v5/pgtype"

type SeenMarker struct {
	AccountID   pgtype.UUID
	WorkspaceID pgtype.UUID
	SeenAt      pgtype.Timestamptz
}
