// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountByEmail = `-- name: AccountByEmail :one
select id, email, name, status, version, created_at, updated_at
from identity.account
where email = $1 and status <> 'archived'
`

func (q *Queries) AccountByEmail(ctx context.Context, email string) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, accountByEmail, email)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const accountByID = `-- name: AccountByID :one
select id, email, name, status, version, created_at, updated_at
from identity.account
where id = $1
`

func (q *Queries) AccountByID(ctx context.Context, id pgtype.UUID) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, accountByID, id)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
insert into identity.account (id, email, name, status, version, created_at, updated_at)
values ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAccountParams struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	Status    string
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateAccount = `-- name: UpdateAccount :execrows
update identity.account
set name = $2, status = $3, version = $4, updated_at = $5
where id = $1 and version = $6
`

type UpdateAccountParams struct {
	ID        pgtype.UUID
	Name      string
	Status    string
	Version   int32
	UpdatedAt pgtype.Timestamptz
	Version_2 int32
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccount,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.Version,
		arg.UpdatedAt,
		arg.Version_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
