// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credential.sql

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const credentialByHash = `-- name: CredentialByHash :one
select id, account_id, kind, hash, name, expires_at, revoked_at, version, created_at, updated_at
from identity.credential
where hash = $1
`

func (q *Queries) CredentialByHash(ctx context.Context, hash string) (IdentityCredential, error) {
	row := q.db.QueryRow(ctx, credentialByHash, hash)
	var i IdentityCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.Hash,
		&i.Name,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const credentialByID = `-- name: CredentialByID :one
select id, account_id, kind, hash, name, expires_at, revoked_at, version, created_at, updated_at
from identity.credential
where id = $1
`

func (q *Queries) CredentialByID(ctx context.Context, id pgtype.UUID) (IdentityCredential, error) {
	row := q.db.QueryRow(ctx, credentialByID, id)
	var i IdentityCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.Hash,
		&i.Name,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const credentialsForAccount = `-- name: CredentialsForAccount :many
select id, account_id, kind, hash, name, expires_at, revoked_at, version, created_at, updated_at
from identity.credential
where account_id = $1
order by created_at desc
`

func (q *Queries) CredentialsForAccount(ctx context.Context, accountID pgtype.UUID) ([]IdentityCredential, error) {
	rows, err := q.db.Query(ctx, credentialsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityCredential{}
	for rows.Next() {
		var i IdentityCredential
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.Hash,
			&i.Name,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCredential = `-- name: InsertCredential :exec
insert into identity.credential (
    id, account_id, kind, hash, name, expires_at, revoked_at, version, created_at, updated_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertCredentialParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Kind      string
	Hash      string
	Name      string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) error {
	_, err := q.db.Exec(ctx, insertCredential,
		arg.ID,
		arg.AccountID,
		arg.Kind,
		arg.Hash,
		arg.Name,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const livePasswordForAccount = `-- name: LivePasswordForAccount :one
select id, account_id, kind, hash, name, expires_at, revoked_at, version, created_at, updated_at
from identity.credential
where account_id = $1 and kind = 'password' and revoked_at is null
`

func (q *Queries) LivePasswordForAccount(ctx context.Context, accountID pgtype.UUID) (IdentityCredential, error) {
	row := q.db.QueryRow(ctx, livePasswordForAccount, accountID)
	var i IdentityCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.Hash,
		&i.Name,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCredential = `-- name: UpdateCredential :execrows
update identity.credential
set hash = $2, name = $3, expires_at = $4, revoked_at = $5, version = $6, updated_at = $7
where id = $1 and version = $8
`

type UpdateCredentialParams struct {
	ID        pgtype.UUID
	Hash      string
	Name      string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	Version   int32
	UpdatedAt pgtype.Timestamptz
	Version_2 int32
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCredential,
		arg.ID,
		arg.Hash,
		arg.Name,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.Version,
		arg.UpdatedAt,
		arg.Version_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
