// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityAccount struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	Status    string
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type IdentityCredential struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Kind      string
	Hash      string
	Name      string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type IdentitySession struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Hash      string
	UserAgent string
	Address   string
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}
