// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSession = `-- name: InsertSession :exec
insert into identity.session (
    id, account_id, hash, user_agent, address, issued_at, expires_at, revoked_at
) values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSessionParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Hash      string
	UserAgent string
	Address   string
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.AccountID,
		arg.Hash,
		arg.UserAgent,
		arg.Address,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	return err
}

const revokeSession = `-- name: RevokeSession :execrows
update identity.session
set revoked_at = $2
where id = $1 and revoked_at is null
`

type RevokeSessionParams struct {
	ID        pgtype.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionsForAccount = `-- name: RevokeSessionsForAccount :many
update identity.session
set revoked_at = $2
where account_id = $1 and revoked_at is null
returning id
`

type RevokeSessionsForAccountParams struct {
	AccountID pgtype.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeSessionsForAccount(ctx context.Context, arg RevokeSessionsForAccountParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, revokeSessionsForAccount, arg.AccountID, arg.RevokedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionByHash = `-- name: SessionByHash :one
select id, account_id, hash, user_agent, address, issued_at, expires_at, revoked_at
from identity.session
where hash = $1
`

func (q *Queries) SessionByHash(ctx context.Context, hash string) (IdentitySession, error) {
	row := q.db.QueryRow(ctx, sessionByHash, hash)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Hash,
		&i.UserAgent,
		&i.Address,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const sessionsForAccount = `-- name: SessionsForAccount :many
select id, account_id, hash, user_agent, address, issued_at, expires_at, revoked_at
from identity.session
where account_id = $1
order by issued_at desc
`

func (q *Queries) SessionsForAccount(ctx context.Context, accountID pgtype.UUID) ([]IdentitySession, error) {
	rows, err := q.db.Query(ctx, sessionsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentitySession{}
	for rows.Next() {
		var i IdentitySession
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Hash,
			&i.UserAgent,
			&i.Address,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
