package domain

import "github.com/0xsj/overwatch-backend/pkg/errors"

var (
	ErrIDRequired                 = errors.New(errors.Invalid, "an identifier is required")
	ErrWorkspaceRequired          = errors.New(errors.Invalid, "assistance belongs to an investigation")
	ErrCaptureRequired            = errors.New(errors.Invalid, "assistance requires one retained capture")
	ErrTextCaptureRequired        = errors.New(errors.Invalid, "assistance requires a retained text capture")
	ErrUnsupported                = errors.New(errors.Invalid, "this assistance operation is not supported for the selected input")
	ErrExternalProviderDisabled   = errors.New(errors.Forbidden, "external assistance providers are disabled for this workspace")
	ErrRetryUnavailable           = errors.New(errors.Conflict, "this assistance operation cannot be retried")
	ErrProviderRequired           = errors.New(errors.Invalid, "an assistance provider is required")
	ErrMethodRequired             = errors.New(errors.Invalid, "an assistance method is required")
	ErrProposalRequired           = errors.New(errors.Invalid, "a proposal requires a statement and exact passage")
	ErrProposalTooLong            = errors.New(errors.Invalid, "an assistance proposal is too long")
	ErrStateUnknown               = errors.New(errors.Invalid, "not an assistance proposal state this system knows")
	ErrDecisionRequired           = errors.New(errors.Invalid, "a proposal review needs a decision")
	ErrDecisionUnknown            = errors.New(errors.Invalid, "not a proposal review decision this system knows")
	ErrReviewRequired             = errors.New(errors.Invalid, "an accepted proposal needs reviewed text")
	ErrCitation                   = errors.New(errors.Invalid, "a proposal passage must match the retained capture exactly")
	ErrCandidateInvalid           = errors.New(errors.Invalid, "an assistance candidate must have a supported type and name")
	ErrSynthesisRequired          = errors.New(errors.Invalid, "a synthesis needs at least one observation")
	ErrSynthesisTooLarge          = errors.New(errors.Invalid, "a synthesis can use at most six observations")
	ErrSynthesisOutput            = errors.New(errors.Invalid, "a synthesis output is too large or invalid")
	ErrSynthesisFailure           = errors.New(errors.Invalid, "a failed synthesis needs a bounded error")
	ErrConnectionReviewRequired   = errors.New(errors.Invalid, "a connection review needs at least one attached observation")
	ErrConnectionReviewTooLarge   = errors.New(errors.Invalid, "a connection review can use at most twelve observations per side")
	ErrConnectionReviewOutput     = errors.New(errors.Invalid, "a connection review output is too large or invalid")
	ErrConnectionReviewRationale  = errors.New(errors.Invalid, "a connection review needs the authored connection rationale")
	ErrQuestionSuggestionRequired = errors.New(errors.Invalid, "question suggestions need at least one unresolved evidence gap")
	ErrQuestionSuggestionTooLarge = errors.New(errors.Invalid, "question suggestion input is too large")
	ErrQuestionSuggestionGap      = errors.New(errors.Invalid, "question suggestion gaps need a label and cited observations")
	ErrQuestionSuggestionOutput   = errors.New(errors.Invalid, "question suggestion output is too large or invalid")
	ErrBriefDraftRequired         = errors.New(errors.Invalid, "a brief draft needs an authored brief and selected observations")
	ErrBriefDraftTooLarge         = errors.New(errors.Invalid, "brief draft input is too large")
	ErrBriefDraftOutput           = errors.New(errors.Invalid, "brief draft output is too large or invalid")
	ErrBriefDraftSection          = errors.New(errors.Invalid, "brief draft changes must name a supported section")
	ErrTimeRequired               = errors.New(errors.Invalid, "assistance requires a creation time")
	ErrNotFound                   = errors.New(errors.NotFound, "assistance operation or proposal")
)
